import { Question, Section } from './types';

// --- STANDARD QUESTIONS (Existing) ---
const rawStandardQuestions = [
  // SECTION 1: 3-32 (Safety Basics & Fire)
  { id: 3, text: "Xodimlar ishlab chiqarish xavfsizligi boshqaruviga bo'ysunishlari va (   ) va operatsion tartib-qoidalarga rioya qilishlari kerak.", type: 'single', options: { A: "Birlikimizning ishlab chiqarish xavfsizligi qoidalari va qoidalari", B: "Kasaba uyushmasi intizomi", C: "Kompaniya ustavi" }, correct: "A" },
  { id: 4, text: "Korxonaning yashirin xavf-xatarini bartaraf etish uchun \"besh joy\" quyidagilarni bildiradi: (   ).", type: 'single', options: { A: "Tuzatish choralari, jarima choralari, mablag'lar, muddatlar va rejalar mavjud", B: "Tuzatish choralari, mas'uliyat, mablag'lar, muddatlar va jazo choralari mavjud", C: "Tuzatish choralari, mas'uliyat, mablag'lar, muddatlar va rejalar mavjud." }, correct: "C" },
  { id: 5, text: "Ish joyi - ishchilar kasbiy faoliyatni amalga oshiradigan va ish beruvchi tomonidan nazorat qilinadigan har qanday joy (   ).", type: 'single', options: { A: "bevosita", B: "to'g'ridan-to'g'ri yoki bilvosita", C: "bilvosita" }, correct: "B" },
  { id: 6, text: "3-darajali xavfli operatsiyalar (qazish ishlari) quyidagilarni o'z ichiga oladi (   )", type: 'single', options: { A: "Poydevorni qazish chuqurligi 0,2 m dan ortiq bo'lgan operatsiyalar", B: "Poydevorni qazish chuqurligi 1,2 m dan ortiq bo'lgan operatsiyalar", C: "Poydevor qazish chuqurligi 2,2 m dan ortiq bo'lgan operatsiyalar", D: "Poydevorni qazish chuqurligi 3,2 m dan ortiq bo'lgan operatsiyalar" }, correct: "B" },
  { id: 7, text: "Uglerod oksidi bilan zaharlanish - tarkibida uglerodli moddalarning to'liq yonmagani mahsulotlarini nafas olish yo'llari orqali nafas olish natijasida yuzaga keladigan zaharlanish, bu asosan inson tanasi (   ) tizimiga zarar etkazadi.", type: 'single', options: { A: "Nafas olish", B: "Hazm qilish", C: "Asabiy" }, correct: "C" },
  { id: 8, text: "Pnevmokoniozning asosiy erta belgilari (   ).", type: 'single', options: { A: "Isitma, burun tiqilishi, oyoq-qo'llarning og'rig'i, yo'tal va balg'am va boshqalar", B: "Yo'tal va balg'am, ko'krak qafasidagi siqilish va ko'krak og'rig'i, nafas olish qiyinlishuvi va boshqalar.", C: "Qovurg'alar ostida og'riq, ishtahani yo'qotish, jigar kattalashishi va boshqalar." }, correct: "B" },
  { id: 9, text: "Yuqori haroratli joylarda tana harorati 39 ° C dan yuqori bo'lgan, to'satdan hushidan ketish, quruq va issiq teri, terlash yo'qligi kabi alomatlari bo'lgan ishchilar (   ) deb baholanishi kerak.", type: 'single', options: { A: "Sovuq", B: "Og'ir issiqlik urishi", C: "Zaharlanish" }, correct: "B" },
  { id: 10, text: "Ish joyidagi shovqin ( ) dB (A) dan oshmasligi kerak. Agar yopiq chegaradan oshsa, himoyani ta'minlash kerak.", type: 'single', options: { A: "80", B: "85", C: "90", D: "95" }, correct: "B" },
  { id: 11, text: "Sigaret qoldig'ining asosiy harorati (   ) ga yetishi mumkin, bu paxta, zig'ir, jun mato, qog'oz, mebel va boshqalar kabi yonuvchan materiallarning yonish nuqtasidan oshadi.", type: 'single', options: { A: "100-200℃", B: "200-300℃", C: "700-800℃" }, correct: "C" },
  { id: 12, text: "Yong'inning dastlabki bosqichi yong'inni o'chirish bosqichidir (   ).", type: 'single', options: { A: "eng noqulay", B: "eng qulay", C: "kamroq qulay" }, correct: "B" },
  { id: 13, text: "Yong'inni o'chirish moslamasi bilan o'chirish uchun eng yaxshi joy (   ).", type: 'single', options: { A: "Shamolga qarshi pozitsiya", B: "Shamolga qarshi yoki o'zaro shamol holati", C: "Yong'in nuqtasidan 10 metrdan uzoqroqda joylashtiring" }, correct: "B" },
  { id: 14, text: "Yong'inni o'chirish uchun o't o'chirgichdan foydalanganda, purkagichni olovga qarating ( ).", type: 'single', options: { A: "Yuqori", B: "O'rta", C: "Ildiz" }, correct: "C" },
  { id: 15, text: "(   ) Yong'inni suv bilan o'chirish olovning kengayishiga olib keladi.", type: 'single', options: { A: "Yog'lar", B: "O'rmonlar", C: "Mebel" }, correct: "A" },
  { id: 16, text: "Aybdorning ehtiyotsizligi tufayli yong'in kelib chiqishiga sabab bo'lgan va og'ir oqibatlarga olib keladigan qilmish (   ).", type: 'single', options: { A: "O't qo'yish jinoyati", B: "yong'in jinoyati", C: "burchni bajarmaslik jinoyati" }, correct: "B" },
  { id: 17, text: "Yong'inni muhofaza qilish to'g'risidagi qonunda yong'indan himoya qilish vositalarining ma'nosiga ko'ra, yong'indan himoya qilish ob'ektlari (   ) o'z ichiga olmaydi.", type: 'single', options: { A: "O't o'chirish mashinasi", B: "Avtomatik yong'in o'chirish tizimi", C: "Yong'in hidranti tizimi" }, correct: "A" },
  { id: 18, text: "Yong'in signalizatsiyasi boshqaruvchisi avtomatik yong'in signalizatsiya tizimidagi asosiy uskuna bo'lib, uning asosiy funktsiyalari ko'p jihatlarni o'z ichiga oladi. To'g'ri javobni tanlang.", type: 'single', options: { A: "Xotira va tanib olish funksiyalari bilan", B: "yong'inga qarshi favqulodda yoritish funksiyasi bilan", C: "tutunning oldini olish va chiqarish, ventilyatsiya va konditsionerlik funktsiyalari bilan" }, correct: "A" },
  { id: 19, text: "Yong'in o'chirish moslamasidagi bosim o'lchagich qizil, sariq va yashil ranglardan foydalanib, o't o'chirgichning bosimini ko'rsatadi. Ko'rsatkich sariq maydonga ishora qilganda bosimni bildiradi (   ).", type: 'single', options: { A: "Oddiy", B: "Yuqori", C: "Past" }, correct: "B" },
  { id: 20, text: "Quruq kukunli yong'inga qarshi vositaning asosiy tarkibiy qismlari natriy bikarbonat va oz miqdorda namlikka chidamli magniy stearati va talk kukunidir. Asosiy printsip (   ).", type: 'single', options: { A: "Asfiksiya", B: "Sovutish", C: "Kimyoviy inhibisyon" }, correct: "C" },
  { id: 21, text: "Karbonat angidridli yong'in o'chirgich kislorod miqdorini kamaytiradi. Odatda, yonishni to'xtatishga olib keladigan kislorod miqdori (   ) dan past bo'lishi kerak.", type: 'single', options: { A: "12%", B: "14%", C: "16%" }, correct: "A" },
  { id: 22, text: "\"Portlash\" deb ataladigan narsa yong'inning qaysi bosqichida sodir bo'ladi? (   )", type: 'single', options: { A: "Dastlabki davr", B: "Rivojlanish davri", C: "Eng yuqori davr" }, correct: "B" },
  { id: 23, text: "Jamoat joylarida o'rnatilgan yong'in favqulodda yoritish uchun uzluksiz elektr ta'minoti vaqti (   ) dan kam bo'lmasligi kerak.", type: 'single', options: { A: "10 daqiqa", B: "15 daqiqa", C: "20 daqiqa" }, correct: "C" },
  { id: 24, text: "Yuqori haroratli ob-havo deganda kunlik maksimal haroratdan ( ) yuqori bo'lgan ob-havo tushuniladi.", type: 'single', options: { A: "33℃", B: "35℃", C: "37℃", D: "40℃" }, correct: "B" },
  { id: 25, text: "Katta zahiraga ega bo'lgan yonuvchan omborlar eshikni o'rnatish oson, bu esa tashqariga ochilishi kerak.", type: 'single', options: { A: "1", B: "2", C: "3" }, correct: "B" },
  { id: 26, text: "Yong'in va portlash sodir bo'lgan baxtsiz hodisalarning oldini olishning asosiy tamoyillari... yong'in va portlash tarqalishining oldini olish va cheklash printsipiga kiruvchi choralar (   ).", type: 'single', options: { A: "Atrof-muhit haroratini qat'iy nazorat qiling", B: "Chaqmoqlardan himoya vositalarini o'rnating", C: "Yong'in signalizatsiya tizimini o'rnating" }, correct: "C" },
  { id: 27, text: "Jabrlangan kishiga birinchi yordam ko'rsatishda birinchi qadam (   ) bo'lishi kerak.", type: 'single', options: { A: "Jabrlanganning hushida yoki yo'qligini kuzating", B: "Qon oqayotgan joyni bog'lang", C: "Yurak massajini o'tkazing" }, correct: "A" },
  { id: 28, text: "Kardiopulmoner reanimatsiya bo'yicha ko'rsatmalarda ko'krak qafasining siqilish chastotasi (   ).", type: 'single', options: { A: "Kamida 80-100 marta/min", B: "Kamida 100 marta/min", C: "Kamida 120 marta/min" }, correct: "B" },
  { id: 29, text: "Kardiopulmoner reanimatsiya bo'yicha ko'rsatmalarda ko'krak qafasining siqilish joyi (   ).", type: 'single', options: { A: "Ko'krak qafasining o'rtasi ko'krak uchlari orasidagi", B: "yurak cho'qqisi", C: "sternumning o'rtasi" }, correct: "A" },
  { id: 30, text: "Katta yoshdagi kardiopulmoner reanimatsiya paytida ko'krak qafasining siqilish chuqurligi (   ).", type: 'single', options: { A: "Ko'krak qafasining anteroposterior diametrining kamida yarmi", B: "3 sm", C: "kamida 5 sm" }, correct: "C" },
  
  // SECTION 7: 181-201 (Violations & Procedures) - Already B Class in text
  { id: 181, text: "Nam purkagich tizimi yopiq tizim bo'lib, unda quvurlar tizimni faollashtirish uchun ishlatiladigan bosimli suv bilan to'ldiriladi. (   )", type: 'boolean', options: { A: "Noto’gri", B: "Tog’ri" }, correct: "A" },
  { id: 182, text: "Ishlab chiqarish korxonasiga xavfsizlik dubulg'asi yoki shikastlangan himoya dubulg'asi kiymasdan kirish.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 183, text: "Xavfsizlik kamarlarini mahkamlamasdan yoki baland yoki past osilgan uskunalardan foydalanmasdan balandlikda (yoki balandlikda) ishlash.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 184, text: "Himoya qo'lqopsiz ammiak suvi, kislota-ishqor eritmasi va xavfli chiqindi suyuqlik kabi xavfli kimyoviy moddalar bilan qo'l bilan aloqa qilish.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 185, text: "Ammiak tanki hududiga, xavfli chiqindilar maydoniga va zaharli gaz ishlab chiqarishi mumkin bo'lgan boshqa joylarga gaz niqobini taqmasdan kirish.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 186, text: "Cho‘kish xavfi mavjud bo‘lgan suv yaqinida ishlaganda qutqaruv ko‘ylagi kiymaslik, belgilangan joyda ishlaganda xavfsizlik kamarini taqmaslik.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 187, text: "Uskunalar va inshootlarni boshqarayotgan yoki ishga tushirish va to'xtatish xodimlari bo'lmagan.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 188, text: "Kuchli shamol, kuchli yomg'ir va chaqmoq kabi og'ir ob-havo sharoitida ochiq havoda yuqori balandlikdagi operatsiyalar.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 189, text: "Kuchli shamol, kuchli yomg'ir va chaqmoq kabi og'ir ob-havo sharoitida ochiq havoda yuqori balandlikdagi operatsiyalar (Takror).", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 190, text: "Xavfli operatsiyani tasdiqlash shakli bo'yicha profilaktika choralari to'liq amalga oshirilmagan va tekshirilmagan.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 191, text: "Xavfli operatsiyaka yoqilgan yoki yoqilgan va xavfli operatsiyani tasdiqlash varaqasi o'z vaqtida imzolanmagan va yopilmagan.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 192, text: "Belgilangan tekshiruvchi yoki xavfli operatsiyalarni tasdiqlovchi ko'rib chiqishni tasdiqlash uchun saytga kelmaydi.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 193, text: "Elektr uzilishidan so'ng kerak bo'lganda uskunani blokirovka qilmaslik yoki belgilab qo'ymaslik.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 194, text: "Asboblar va jihozlar ishlashdan oldin tekshirilmaydi, asboblar va jihozlarda potentsial xavfsizlik xavfi mavjud.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 195, text: "Muddati o'tgan yoki sinovdan o'ta olmagan asboblar bilan ishlash.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 196, text: "Kislorod va asetilen quvurlari ko'plab yoriqlar bilan shikastlangan, bosimni pasaytiradigan valflar va bosim o'lchagichlari shikastlangan va haroratni pasaytirish moslamasi yo'q.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 197, text: "Yuk ko'tarish operatsiyalari bo'yicha qo'mondonlik xodimlari maxsus tayyorgarlikdan o'tmagan va zaruriy sertifikat olmagan.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 198, text: "Ogohlantirish va ogohlantiruvchi belgilarsiz yuk ko'tarish ish joyida o'rnatilmagan.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 199, text: "Yuk ko'tarishdan oldin sinov ko'tarilishi tasdiqlanmagan.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 200, text: "Zavodda tezlikni oshirish, ortiqcha yuk ko'tarish va piyodalarga yo'l bermaslik.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
  { id: 201, text: "Boshqaruv xodimlari “uchta qoidabuzarlik”ga ko‘z yumib, ularni to‘xtatmadilar, tuzatmadilar.", type: 'single', options: { A: "\"A\" toifasidagi qoidabuzarlik.", B: "\"B\" toifasidagi qoidabuzarlik.", C: "\"C\" toifasidagi qoidabuzarlik.", D: "\"D\" toifasidagi qoidabuzarlik." }, correct: "B" },
];

// --- AZIMXON MODE QUESTIONS (Mixed A, B, C Class Violations) ---
// IDs 301-364: Mostly A-Class (Severe)
// IDs 365-385: B-Class (Moderate/Procedural)
// IDs 386-400: C-Class (Minor/Administrative)

const azimxonRawList = [
  // --- A TOIFA (Qo'pol Qoidabuzarliklar) ---
  { id: 301, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Uskunada (yoki uning atrofida) mumkin bo'lgan aloqa ishlarini bajarish va uskunaning elektr ta'minotini uzish tartib-qoidalaridan o'tmaslik\"?", correct: 'A' },
  { id: 302, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Pirotexnika vositalarini ishlatish taqiqlangan yonuvchan va portlash xavfli joylarda chekish yoki qoidalarni buzgan holda olov yoqish\"?", correct: 'A' },
  { id: 303, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Mast holda haydash, litsenziyasiz haydash\"?", correct: 'A' },
  { id: 304, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Sinfda ichish yoki ichishdan keyin ishlab chiqarish maydoniga kirish\"?", correct: 'A' },
  { id: 305, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Xavfsizlik testida aldash yoki boshqalarga yordam berish\"?", correct: 'A' },
  { id: 306, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Ish vaqtida ish joyida uxlash\"?", correct: 'A' },
  { id: 307, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Voris lavozimni ruxsatsiz tark etadi\"?", correct: 'A' },
  { id: 308, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Huquqbuzarliklarga yo'l qo'ymaslik, xavfsizlikni boshqarish xodimlarini qasddan haqorat qilish, qo'rqitish yoki tahdid qilishga quloq solmang\"?", correct: 'A' },
  { id: 309, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Xavfsizlik hodisasi sodir bo'lganda, navbatchi boshqaruv xodimlarining ma'lumotlarini uzatish yoki hisoboti o'z vaqtida emas\"?", correct: 'A' },

  // --- B TOIFA (O'rta Qoidabuzarliklar) ---
  { id: 310, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Ishlab chiqarish korxonasiga xavfsizlik dubulg'asi yoki shikastlangan himoya dubulg'asi kiymasdan kirish\"?", correct: 'B' },
  { id: 311, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Xavfsizlik kamarlarini mahkamlamasdan yoki baland yoki past osilgan uskunalardan foydalanmasdan balandlikda (yoki balandlikda) ishlash\"?", correct: 'B' },
  { id: 312, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Himoya qo'lqopsiz ammiak suvi, kislota-ishqor eritmasi va xavfli chiqindi suyuqlik kabi xavfli kimyoviy moddalar bilan qo'l bilan aloqa qilish\"?", correct: 'B' },
  { id: 313, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Uskunalar va inshootlarni boshqarayotgan yoki ishga tushirish va to'xtatish xodimlari bo'lmagan\"?", correct: 'B' },
  { id: 314, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Kuchli shamol, kuchli yomg'ir va chaqmoq kabi og'ir ob-havo sharoitida ochiq havoda yuqori balandlikdagi operatsiyalar\"?", correct: 'B' },
  { id: 315, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Asboblar va jihozlar ishlashdan oldin tekshirilmaydi, asboblar va jihozlarda potentsial xavfsizlik xavfi mavjud\"?", correct: 'B' },
  { id: 316, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Muddati o'tgan yoki sinovdan o'ta olmagan asboblar bilan ishlash\"?", correct: 'B' },
  { id: 317, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Kislorod va asetilen quvurlari ko'plab yoriqlar bilan shikastlangan, bosimni pasaytiradigan valflar va bosim o'lchagichlari shikastlangan va haroratni pasaytirish moslamasi yo'q\"?", correct: 'B' },
  { id: 318, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Kislorod va asetilen tsilindrlari 5 metrdan kamroq masofada, ochiq olovdan 10 metrdan kamroq masofada joylashgan va yuqori haroratli havoda quyoshga ta'sir qiladi\"?", correct: 'B' },
  { id: 319, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Ko'taruvchi narsalar va kran qo'llari ostida qolish va o'tish\"?", correct: 'B' },
  { id: 320, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Elektr jihozlaridan xavfsizlikni muhofaza qilish moslamalarisiz yoki himoya vositalari ishlamay qolgan holda foydalaning\"?", correct: 'B' },
  { id: 321, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Zararlangan simlar o'z vaqtida aloqa qilmaydi yoki ortiqcha yuklanadi\"?", correct: 'B' },
  { id: 322, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Zavodda tezlikni oshirish, ortiqcha yuk ko'tarish va piyodalarga yo'l bermaslik\"?", correct: 'B' },
  { id: 323, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Zavod hududida litsenziyasiz mototsikl va shaxsiy avtomobillarni boshqarish\"?", correct: 'B' },
  { id: 324, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Kelishuvsiz yoki roziliksiz lavozimlarni egallash yoki o'zgartirish\"?", correct: 'B' },
  { id: 325, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Boshqaruv xodimlari “uchta qoidabuzarlik”ga ko‘z yumib, ularni to‘xtatmadilar, tuzatmadilar\"?", correct: 'B' },
  { id: 326, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Qoidalarni buzgan holda tergov bilan hamkorlik qilmaslik yoki baxtsiz hodisalar\"?", correct: 'B' },

  // --- C TOIFA (Yengil Qoidabuzarliklar) ---
  { id: 327, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Ishlab chiqarish maydoniga kirish yoki ma'lum bir hududda ishlash tegishli ish kiyimlarini to'g'ri kiymaydi\"?", correct: 'C' },
  { id: 328, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Baland joyga qo'yilgan buyumlar tartibsiz bo'lib, baland joydan yiqilib, odamlarga shikast etkazish xavfi mavjud\"?", correct: 'C' },
  { id: 329, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Oddiy ish sharoitida kranlar va poezd yo'llari kabi xavfli joylarda qolish yoki dam olish\"?", correct: 'C' },
  { id: 330, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"O'z xohishiga ko'ra uskunaning nomi va seriya raqamini qo'shish va o'zgartirish\"?", correct: 'C' },
  { id: 331, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Ishlashdan oldin xavfsizlik texnologiyasini oshkor qilmaslik yoki xavfsizlik choralarining bajarilishini tasdiqlamaslik\"?", correct: 'C' },
  { id: 332, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Profilaktik chora-tadbirlar bo'yicha ma'lumot olmagan yoki joylarda xavfsizlikni oshkor qilishni qabul qilmagan operatorlar mavjud\"?", correct: 'C' },
  { id: 333, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Kislorod va asetilen idishlari quyish moslamalari, shisha qopqoqlari va vibratsiyaga qarshi halqalarsiz ishlatiladi va saqlanadi\"?", correct: 'C' },
  { id: 334, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Xavfsizlikni muhofaza qilish inshootlarini ruxsatsiz demontaj qilish yoki demontajdan keyin ularni o'z vaqtida tiklamaslik\"?", correct: 'C' },
  { id: 335, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Avtomobil chorrahaga ketayotganda, haydash xavfli bo'lib, 'bir qarash, ikkita sekin, uch o'tish' ga erishmaydi\"?", correct: 'C' },
  { id: 336, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Noqonuniy to'xtash joyi yo'l harakatiga ta'sir qiladi\"?", correct: 'C' },
  { id: 337, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Zavoddagi parker dvigatelni o'chira olmaydi va chiqib ketgandan keyin eshikni o'z vaqtida qulflash uchun kalitni tortib oladi\"?", correct: 'C' },
  { id: 338, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Zavod hududida bir qo'l bilan mototsikllar, akkumulyatorli avtomobillar va velosipedlarni haydash, mototsikl va akkumulyatorli avtomobillarni haydashda himoya dubulg'alarini taqmaslik\"?", correct: 'C' },
  { id: 339, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Bir qo'l bilan javob berish va zavod hududida haydash paytida qo'ng'iroq qilish (avtobus tashqariga chiqish)\"?", correct: 'C' },
  { id: 340, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Ish joyida jang qilish va o'yin o'ynash ishning xavfsizligiga ta'sir qiladi\"?", correct: 'C' },
  { id: 341, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"ruxsatsiz xavfsizlik belgilarini ataylab buzish yoki xavfsizlikni muhofaza qilish vositalarini demontaj qilish\"?", correct: 'C' },
  { id: 342, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Ayol xodimlar ishlab chiqarish maydoniga borganlarida yoki uskunani ishlatganda, ular butun sochlarini dubulg'aga qo'ymaydilar\"?", correct: 'C' },
  { id: 343, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Bo'lim rahbarlari yuqori harorat mavsumida issiqlik urishining oldini oluvchi dori-darmonlarni chiqarmagan\"?", correct: 'C' },
  { id: 344, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Zinadan tutqichsiz yuqoriga va pastga tushish\"?", correct: 'C' },
  { id: 345, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Belgilangan xavfsizlik zinapoyalari joylarda operatsiyalar uchun ishlatilmaydi\"?", correct: 'C' },

  // --- D TOIFA (Ogohlantirishlar) ---
  { id: 346, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Ishlab chiqarish korxonasiga kombinezon yoki aks ettiruvchi jilet kiymasdan kirish\"?", correct: 'D' },
  { id: 347, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Ishlab chiqarish maydoniga kirganda, xavfsizlik dubulg'asining peshona tasmasi mahkamlanmagan\"?", correct: 'D' },
  { id: 348, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Tegishli xavfsizlik poyafzallarini kiymasdan yoki xavfsizlik poyabzali shikastlangan yoki yaroqsiz holda ishlab chiqarish joyiga kirish\"?", correct: 'D' },
  { id: 349, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"To'g'ri quloq himoyasi taqmasdan shovqin xavfli hududga kirish\"?", correct: 'D' },
  { id: 350, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Chang xavfli hududlarga kirishda himoya niqoblarini to'g'ri taqmaslik\"?", correct: 'D' },
  { id: 351, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Xavfli manba hududida o'rnatilgan yong'inga qarshi uskunalarni ruxsatsiz o'zlashtirish yoki vaqtincha o'zlashtirishdan keyin o'z vaqtida tiklanmaslik\"?", correct: 'D' },
  { id: 352, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Yiqilish sodir bo'lganda, xavfli hudud ostida qolish yoki dam olish, masalan, kamar koridori\"?", correct: 'D' },
  { id: 353, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Sinf oldi yig'ilishida xavfsizlik bo'yicha ta'lim o'tkazilmagan va xavfsizlik choralarini amalga oshirmagan\"?", correct: 'D' },
  { id: 354, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Muammolar yoki shikastlanishlar mavjud bo'lsa, ishlatilgan asboblarni o'z vaqtida xabar qilmaslik va ta'mirlash\"?", correct: 'D' },
  { id: 355, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Xavfsizlik va profilaktika choralarini tashkil etish va amalga oshirmaslik bilan birga ishlarni tashkil etish\"?", correct: 'D' },
  { id: 356, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Zavod hududida odamlar va transport vositalari ajratilgan bo'limda piyodalar yo'laklaridan foydalanilmaydi\"?", correct: 'D' },
  { id: 357, text: "Quyidagi qoidabuzarlik qaysi toifaga kiradi: \"Yuqori haroratli mavsumlarda ishchilar issiqlik urishining oldini olish va sovutish uchun dori-darmonlarni o'zlari bilan olib yurishmagan\"?", correct: 'D' },
];

const rawAzimxonQuestions = azimxonRawList.map(q => ({
  ...q,
  type: 'single',
  options: {
    A: "A TOIFA (Qo'pol Qoidabuzarlik)",
    B: "B TOIFA (O'rta Qoidabuzarlik)",
    C: "C TOIFA (Yengil Qoidabuzarlik)",
    D: "D TOIFA (Ogohlantirish)"
  },
  correctAnswer: q.correct
}));

// --- ISLOMBOY MODE QUESTIONS (New) ---
const rawIslomboyQuestions = [
  // General Safety & Procedures
  { id: 1001, text: "Xuddi shu ishchi guruhda kichik jarohatlar xavfsizligi bo'yicha baxtsiz hodisa sodir bo'lgandan so'ng, bu haqda bo'linmaning xavfsizlikni boshqarish xodimlariga yoki mas'ul shaxsga xabar berish kerak.", type: 'single', options: { A: "2 soat", B: "1 soat", C: "24 soat", D: "darhol" }, correct: "D" },
  { id: 1002, text: "Ishlab chiqarish jarayonida va mehnat jarayonida ishchilarning sog'lig'iga xavf tug'diradigan omillar ( ) kasbiy xavf deyiladi.", type: 'single', options: { A: "Gigiena muhiti", B: "Mehnat muhiti", C: "Oila muhit" }, correct: "B" },
  { id: 1003, text: "Qoidalar va qoidalarga e'tibor bermaslik va qoidalarni bila turib buzish ko'pincha baxtsiz hodisalarga olib keladi ( ).", type: 'single', options: { A: "Inson omillari", B: "Atrof-muhit omillari", C: "Ob'ektlarning xavfli sharoitlari" }, correct: "A" },
  { id: 1004, text: "Mexanik tishli uzatish tuzilishida ( ) eng xavfli joy.", type: 'single', options: { A: "Old g'ildirak ostida", B: "Old g'ildirak ustida", C: "Ikki g'ildirak bir-biriga yopisha boshlaydi" }, correct: "C" },
  { id: 1005, text: "Yong'inning dastlabki bosqichi yong'inni o'chirish bosqichidir ( ).", type: 'single', options: { A: "eng noqulay", B: "eng qulay", C: "kamroq qulay" }, correct: "B" },
  { id: 1006, text: "Chang bilan ishlaganda uni ( ) taqing.", type: 'single', options: { A: "Paxta doka niqob", B: "Filtr chang niqobi", C: "Gaz niqobi" }, correct: "B" },
  { id: 1007, text: "Tungi ish uchun yorug'likning etarli emasligi ish xavfsizligiga ta'sir qiladi. ( )", type: 'single', options: { A: "To’g’ri", B: "Noto’g’ri" }, correct: "A" },
  { id: 1008, text: "Xavfsizlik tekshiruvlari asosan fikrlarni tekshirish, boshqaruvni tekshirish, tizimlarni tekshirish, yashirin xavflarni tekshirish va tekshirish ( ) kabi jihatlardan amalga oshiriladi", type: 'single', options: { A: "Tajriba", B: "Buzilish", C: "Baxtsiz hodisalarni bartaraf etish" }, correct: "C" },
  { id: 1009, text: "Korxonada profilaktika ishlari olib borilganda... Lining xatti-harakati ( ) ni tashkil etishda gumon qilinmoqda.", type: 'single', options: { A: "Katta javobgarlik bilan bog'liq baxtsiz hodisa jinoyati", B: "Umumiy javobgarlik bilan bog'liq baxtsiz hodisa jinoyati", C: "Noqonuniy va xavfli operatsiyalarni majburlash jinoyati" }, correct: "A" },
  { id: 1010, text: "Quyidagi mexanik xavfsizlikni himoya qilish qurilmalari orasida faqat operatorni himoya qila oladigan qurilma ( ).", type: 'single', options: { A: "Qulflangan xavfsizlik moslamasi", B: "Ikki qo'l bilan boshqaruvchi xavfsizlik moslamasi", C: "Avtomatik xavfsizlik moslamasi" }, correct: "B" },
  { id: 1011, text: "Yonuvchan va portlovchi joylarda ( ) kiyish eng xavflidir.", type: 'single', options: { A: "mato poyafzallari", B: "rezina poyabzal", C: "shpilkali poyabzal" }, correct: "C" },
  { id: 1012, text: "( ) Yonuvchan va portlovchi joylarda kiyish mumkin emas.", type: 'single', options: { A: "Sof paxta ish kiyimlari", B: "Kimyoviy tolali ish kiyimlari", C: "Antistatik ish kiyimlari" }, correct: "B" },
  { id: 1013, text: "Korroziv mahsulotlarni yuklash va tushirishda qo'lqop kiyish kerak.( )", type: 'single', options: { A: "Kanvas", B: "Kauchuk", C: "Paxta" }, correct: "B" },
  { id: 1014, text: "Kimyoviy va tsement zavodlarining portlashdan himoyalangan jarayonlarida yaxshi shamollatish bilan portlashga qarshi choralar ko'riladi. Maqsad ( )", type: 'single', options: { A: "Oksidlovchilarni yo'q qilish", B: "Havodagi yonuvchi moddalar kontsentratsiyasini nazorat qilish", C: "Dastgoh haroratini pasaytirish" }, correct: "B" },
  { id: 1015, text: "Favqulodda qutqaruv respiratorlari odatda taxminan ( ) havo etkazib berish vaqtini ta'minlaydi.", type: 'single', options: { A: "15 daqiqa", B: "5 daqiqa", C: "8 daqiqa", D: "10 daqiqa" }, correct: "A" },
  { id: 1016, text: "Darajadan ( ) kuchli shamollar yoki kuchli qor, kuchli yomg'ir yoki tuman kabi og'ir ob-havoga duch kelganda, balandlikda ochiq ish bilan shug'ullanmang.", type: 'single', options: { A: "uch", B: "to'rt", C: "besh", D: "olti" }, correct: "D" },
  { id: 1017, text: "Ombordagi yoritish moslamalari orasidagi vertikal masofa va saqlanadigan narsalar orasidagi gorizontal masofa ( ) metrdan kam bo'lmasligi kerak.", type: 'single', options: { A: "0.3", B: "0.4", C: "0.5" }, correct: "C" },
  { id: 1018, text: "Xavfsizlik muhofazasi, sug'urta, signalizatsiya va boshqa qurilmalarning yo'qligi... baxtsiz hodisadan. ( )", type: 'single', options: { A: "Odamlarning xavfli xatti-harakatlari", B: "Ishlarning xavfli sharoitlari", C: "Boshqaruvdagi kamchiliklar" }, correct: "B" },
  { id: 1019, text: "Chang va zaharli xavflarni keltirib chiqaradigan jarayonlar... ( ) singdirish va tozalash kabi samarali kompleks choralar qabul qilinishi kerak.", type: 'single', options: { A: "Yuqori bosim", B: "Nol bosim", C: "Salbiy bosim" }, correct: "C" },
  
  // Conveyor & Mechanical (IDs 1020-1050 range)
  { id: 1020, text: "Tasmada kesib o'tishga yo'l qo'yilmaydi, lenta konveyeridan o'tishga ruxsat etilmaydi ( ).", type: 'single', options: { A: "yuqorida", B: "pastda", C: "ish vaqti" }, correct: "B" },
  { id: 1021, text: "Kirishlari kattaroq va uzunroq bo'lgan kamarlar uchun maxsus ko'rsatmalar ( ) shakllantirilishi kerak.", type: 'single', options: { A: "Qurilish rejasi", B: "Xavfsizlik rejasi", C: "Qurilish rejasi" }, correct: "B" },
  { id: 1022, text: "Tasmali konveyer qo'zg'alganda va to'xtaganda, ( ) mashina xavfsiz va to'g'ri ekanligini tasdiqlash... kerak.", type: 'single', options: { A: "Xodimlarni joylashtirish", B: "Operator", C: "Bo'lim menejeri" }, correct: "B" },
  { id: 1023, text: "Tasmali konveyerga texnik xizmat ko'rsatish vaqtida istisnolar qilingan ( ) va barcha xavfsizlik choralari ko'rilgan.", type: 'single', options: { A: "Ko'rsatmalar", B: "Ishga ariza", C: "Uskunaning elektr ta'minoti uzilishi" }, correct: "C" },
  { id: 1024, text: "Tasmali konveyer qarama-qarshi og'irlik rolikini tortganda va uni ko'targanda, operator ( ) rolik kabi aylanadigan qismlarda turadi.", type: 'single', options: { A: "Ehtiyotkorlik", B: "Xavfsizlik sharoitida", C: "Qattiq taqiqlangan" }, correct: "C" },
  { id: 1025, text: "Tasmali konveyer ishlayotganida, tasmali konveyer uskunasidagi ( ) proyeksiya maydonidan inson tanasining hech bir qismi o'tishi mumkin emas.", type: 'single', options: { A: "Pastga vertikal", B: "Yuqoriga vertikal", C: "Vertikal" }, correct: "A" },
  { id: 1026, text: "Uskunaga texnik xizmat ko'rsatish vaqtida uskunani o'chirish va texnik xizmat ko'rsatish tugmasi ( ) holatiga o'rnatilishi kerak.", type: 'single', options: { A: "Markaziy boshqaruv", B: "Xizmat", C: "Saytda" }, correct: "B" },
  { id: 1027, text: "Tasmani ishga tushirishga yordam berish uchun ( ) dan foydalanish taqiqlanadi.", type: 'single', options: { A: "Mobil dvigatel", B: "Ko'targich", C: "Ish kuchi" }, correct: "C" },
  { id: 1028, text: "Kamar ishlayotganda ( ), to'g'ridan-to'g'ri quyida joylashgan qo'riqxonada to'plangan materialni tozalang.", type: 'single', options: { A: "OK", B: "Qat'iy taqiqlangan", C: "Rejalashtirilgan" }, correct: "B" },
  { id: 1029, text: "Rejalashtirilgan ta'mirlashni amalga oshirishdan oldin materiallar ( ) bo'lishi kerak.", type: 'single', options: { A: "Bo'sh", B: "Toza", C: "Kamarga joylashtiring" }, correct: "A" },
  { id: 1030, text: "Xavfsizlik ( ) to'g'ridan-to'g'ri tarmoqli konveyer qarshi og'irligi ostida o'rnatilishi kerak", type: 'single', options: { A: "Himoya panjarasi", B: "kordon", C: "yopish choralari" }, correct: "A" },
  { id: 1031, text: "Bir kishi tozalovchi materiallarga, ikkinchisi esa ( ) uchun javobgardir.", type: 'single', options: { A: "Elektr uzilish tartib-qoidalarini bajaring", B: "Eslatma buyurtmalarini bajaring", C: "Saytda monitoring" }, correct: "C" },
  { id: 1033, text: "Tasmali konveyerni ishga tushirishdan oldin uskunani tekshirish kerak ( )...", type: 'single', options: { A: "Kompleks tekshirish", B: "Ehtiyotkorlik bilan tekshirish", C: "Tezkor tekshirish" }, correct: "A" },
  { id: 1034, text: "Tasmali konveyerni ishga tushirishdan oldin qo'ng'iroq ( ) soniya jiringlashi kerak", type: 'single', options: { A: "15", B: "20", C: "25", D: "30" }, correct: "D" },
  { id: 1036, text: "Platforma panjarasi kamida ( ) metrdan baland bo'lishi kerak.", type: 'single', options: { A: "1,2", B: "1,4", C: "1,6", D: "1,8" }, correct: "A" },
  { id: 1038, text: "Mexanik ishlov berish zavodidagi shovqin juda baland... ustuvor ahamiyat berishlari kerak: ( )", type: 'single', options: { A: "Shovqin intensivligini kamaytiring", B: "Yuqori va past joylarni ajrating", C: "Ishchilarning aylanish tizimi" }, correct: "A" },
  
  // True/False & Technical (1054-1060)
  { id: 1054, text: "Ishga kirishishdan oldin uskunani tekshirish va qo'ng'iroqqa javob berish kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1055, text: "Yuk ko'tarish burilish radiusida odamlar bo'lishi mumkin.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1056, text: "Uskunani tozalashda aylanuvchi qismlarga tegmang va panjaralarni mahkam ushlang.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1057, text: "Asbob nuqsonli bo'lsa, uni ishlatishda xavfsizlikka e'tibor bering.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1058, text: "Rejalashtirilgan ta'mirlashni amalga oshirishdan oldin materiallar drenajlanishi kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1059, text: "Operatorning o'zi uchun... katta xavf tug'diradigan operatsiyalar qiyin operatsiyalar deb ataladi.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1060, text: "Energiya izolyatsiyasi bitta odam, bitta qulf tamoyiliga amal qiladi. Shaxsiy qulflar o'zingiz tomonidan saqlanadi...", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },

  // First Aid & Fire (1061-1100)
  { id: 1061, text: "Xodimlar ishlab chiqarish xavfsizligi boshqaruviga bo'ysunishlari va ( ) va operatsion tartib-qoidalarga rioya qilishlari kerak.", type: 'single', options: { A: "Korxonamiz qoidalari", B: "Kasaba uyushmasi", C: "Kompaniya ustavi" }, correct: "A" },
  { id: 1062, text: "Yuqori haroratli joylarda... ( ) deb baholanishi kerak.", type: 'single', options: { A: "Sovuq", B: "Og'ir issiqlik urishi", C: "Zaharlanish" }, correct: "B" },
  { id: 1063, text: "Yong'inning dastlabki bosqichi yong'inni o'chirish bosqichidir ( ).", type: 'single', options: { A: "eng noqulay", B: "eng qulay", C: "kamroq qulay" }, correct: "B" },
  { id: 1064, text: "Ko'rsatkich sariq maydonga ishora qilganda bosimni bildiradi ( ).", type: 'single', options: { A: "Oddiy", B: "Yuqori", C: "Past" }, correct: "B" },
  { id: 1065, text: "Jabrlangan kishiga birinchi yordam ko'rsatishda birinchi qadam ( ) bo'lishi kerak.", type: 'single', options: { A: "Jabrlanganning hushida yoki yo'qligini kuzating", B: "Qon oqayotgan joyni bog'lang", C: "Yurak massajini o'tkazing" }, correct: "A" },
  { id: 1066, text: "Kimdir yonib ketganda, yong'inni o'chirishning quyidagi usullaridan qaysi biri noto'g'ri? ( )", type: 'single', options: { A: "Joyda dumalab oling", B: "Og'ir kiyimlar bilan yoping", C: "Tez shamolga yuguring" }, correct: "C" },
  { id: 1067, text: "Siz kuyganingizda, birinchi yordamning to'g'ri usuli ( ) bo'lishi kerak.", type: 'single', options: { A: "Kuygan joyni iloji boricha tezroq sovuq suv bilan yuvib tashlang", B: "Og'zingiz bilan puflang", C: "Kasalxonaga boring" }, correct: "A" },
  { id: 1068, text: "Barmoqni kesish baxtsiz hodisasi sodir bo'lgandan so'ng... ( ) to'g'ri.", type: 'single', options: { A: "Kasalxonaga yuboring", B: "Doka bilan o'rab, toza paketga soling va past haroratda saqlang", C: "Sho'r suvga soling" }, correct: "B" },
  { id: 1069, text: "Singandan so'ng, singan suyakni tezda tuzatish kerak va fiksatsiya paytida ( ) saqlanishi kerak.", type: 'single', options: { A: "Iloji boricha mahkam", B: "iloji boricha bo'sh", C: "mos ravishda mahkamlang" }, correct: "C" },
  { id: 1070, text: "Sanoat zaharlarining inson tanasiga kirishining uchta yo'li mavjud, ya'ni ( ).", type: 'single', options: { A: "Oziq-ovqat, kiyim", B: "og'iz, burun", C: "nafas olish yo'llari, teri, ovqat hazm qilish tizimi" }, correct: "C" },
  { id: 1072, text: "Quruq kukunli yong'inga qarshi vosita... yong'inni o'chirish mexanizmiga tegishli bo'lmagani ( )", type: 'single', options: { A: "Bo'g'ilish", B: "Sovutish", C: "Izolyatsiya", D: "Suyultirish" }, correct: "D" },
  { id: 1073, text: "Yong'in avariya yoritgichlari... o'tish vaqti ( ) dan oshmasligi kerak.", type: 'single', options: { A: "0.25S", B: "1s", C: "3S", D: "5s" }, correct: "D" },
  { id: 1074, text: "Yonuvchan moddalarni isitish... tashqi uchqunlar, olov va boshqa tutashuv manbalarisiz saqlash natijasida yonishi ( ) deyiladi.", type: 'single', options: { A: "Portlash", B: "O'z-o'zidan yonish", C: "Chaqnoq yong'in" }, correct: "B" },
  { id: 1075, text: "Shamlarning yonish shakli eng ko'p uchraydi ( ).", type: 'single', options: { A: "Bug'lanishli yonish", B: "Yuzaki yonish", C: "Parchalanish yonishi" }, correct: "A" },
  { id: 1082, text: "Agar kimdir elektr toki urganligi aniqlansa, birinchi qadam ( ).", type: 'single', options: { A: "Tez yordam chaqiring", B: "Elektr ta'minotini uzing", C: "Sun'iy nafas oling" }, correct: "B" },
  { id: 1084, text: "Konsentrlangan sulfat kislota teriga sepilganda quyidagi usuldan foydalanish kerak ( )", type: 'single', options: { A: "Darhol suv bilan yuving", B: "Kasalxonaga boring", C: "Mato bilan artib, keyin yuving" }, correct: "C" },
  { id: 1085, text: "Quyidagi ( ) qon ketish eng xavfli hisoblanadi...", type: 'single', options: { A: "kapillyar", B: "venoz", C: "arterial" }, correct: "C" },
  { id: 1087, text: "Sizning kiyimingiz yonayotganda, quyidagi yong'inni o'chirish usullari orasida ( ) to'g'ri.", type: 'single', options: { A: "Tez yugurib", B: "olovni qo'llaringiz bilan uring", C: "olovni o'chirish uchun joyida dumalang" }, correct: "C" },

  // Traffic & Vehicles (1165-1181)
  { id: 1165, text: "Tog'li hududda muzli va qorli yo'lda... oldingizda turgan transport vositasiga duch kelganingizda nima qilish kerak?", type: 'single', options: { A: "Oldindagi transport vositasi o'tib ketgandan so'ng nishabga chiqing", B: "Past tezlikda quvib o'tish", C: "Yaqinroq chiqing" }, correct: "A" },
  { id: 1166, text: "Svetoforlar: Qizil, Yashil, Sariq. (A) o'tish yo'q, () ruxsat, () ogohlantirish ma'nosini bildiradi.", type: 'single', options: { A: "qizil; yashil; sariq", B: "yashil; qizil; sariq", C: "qizil; sariq; yashil" }, correct: "A" },
  { id: 1167, text: "Muzli va qorli yo'llarda harakatlanayotganda nimalarga e'tibor berish kerak?", type: 'single', options: { A: "Yo'lda yopishishning kuchayishi", B: "Kengaytirilgan tormozlash masofasi", C: "Tormozlash unumdorligi o'zgarmasligi" }, correct: "B" },
  { id: 1168, text: "Loyli yo'l xavfsiz haydashga qanday ta'sir qiladi?", type: 'single', options: { A: "Yo'lning yopishishi kuchayadi", B: "Haydash qarshiligi pasayadi", C: "G'ildiraklar osongina sirpanadi" }, correct: "C" },
  { id: 1169, text: "Yomg'irdan keyin yo'l yuzasi sirpanchiq... favqulodda tormozlanish sodir bo'lsa nima bo'lishi mumkin?", type: 'single', options: { A: "E'tibor bermaslik", B: "Ko'rishning xiralashishi", C: "Dvigatel to'xtab qolishi", D: "Sirpanish va YTH" }, correct: "D" },
  { id: 1170, text: "Dvigatel yonib ketgandan keyin birinchi navbatda nima qilish kerak?", type: 'single', options: { A: "Dvigatelni tezda o'chiring", B: "Shamol ostida olovni o'chiring", C: "Olovni suv bilan o'chiring" }, correct: "C" },
  { id: 1171, text: "Haydash paytida dvigatel to'satdan to'xtab qolsa nima qilish kerak?", type: 'single', options: { A: "Neytral holat", B: "To'xtash uchun sekin sekinlashtiring", C: "Favqulodda tormozlash" }, correct: "B" },
  { id: 1172, text: "Avtomobil moy trubkasi yonib ketganda, yong'inni o'chirish uchun ( ) dan foydalaning.", type: 'single', options: { A: "Quruq kukunli yong'inga qarshi vosita", B: "Karbonat angidrid", C: "Suv" }, correct: "B" },
  { id: 1173, text: "Haydashdan oldin shinalarning qaysi jihatlarini tekshirish kerak?", type: 'single', options: { A: "Hech narsa", B: "Mahkamlash va havo bosimi", C: "Zaxira shina" }, correct: "B" },
  { id: 1174, text: "Rulda boshqaruvini yo'qotgandan so'ng... qanday qilib to'xtatish kerak?", type: 'single', options: { A: "Tezda vitesni oling", B: "Qat'iy qadam qo'ying va tormoz pedalini bo'shashtiring", C: "Tormoz pedalini engil bosib turing" }, correct: "B" },
  { id: 1175, text: "Kechasi ko'cha chiroqlari yo'q yo'lda... uzoq nurni ( ) o'chirib, past nurga o'tishi kerak.", type: 'single', options: { A: "50 metr", B: "200 metr", C: "150 metr" }, correct: "C" },
  { id: 1176, text: "Avtomobil sirpanib ketsa, qaysi fikr to'g'ri?", type: 'single', options: { A: "Rul g'ildiragini sirg'anayotgan tomonga burang", B: "Rulni teskari burang", C: "Tez tormozlang" }, correct: "A" },
  { id: 1177, text: "Haydash paytida signal yoki chiroq ishlamay qolsa, ( ).", type: 'single', options: { A: "Haydashda davom etish mumkin", B: "To'xtamasdan haydash", C: "To'xtatib, ta'mirlashingiz kerak" }, correct: "C" },
  { id: 1178, text: "Quvib o'tishda oldinda turgan transport vositasi sekinlashmaydi, bu kerak ( ).", type: 'single', options: { A: "Majburiy quvib o‘tish", B: "O‘tib ketishni to‘xtating", C: "Signal bering" }, correct: "B" },
  { id: 1179, text: "Tog'lar yaqinidagi xavfli yo'llarda tormoz ishlamay qolsa ( ) kerak.", type: 'single', options: { A: "Mashinadan tushing", B: "Dvigatelni o'chiring", C: "Past vitesni oling" }, correct: "C" },
  { id: 1180, text: "Avtomobil suvga tushganidan keyin tormoz effektini tiklash uchun nima qilish kerak?", type: 'single', options: { A: "Doimiy og'ir teginish", B: "Vaqti-vaqti bilan kuchli teginish", C: "Vaqti-vaqti bilan tegish" }, correct: "C" },
  { id: 1181, text: "Kechasi tor yo'lda qarama-qarshi tomondan kelayotgan motorsiz transport vositasiga duch kelganda...", type: 'single', options: { A: "Ogohlantirish chiroqlari", B: "Past nurni ishlating, sekinlashtiring", C: "Uzoq va past nurni almashtiring" }, correct: "B" },

  // Traffic True/False (1182-1200)
  { id: 1182, text: "Ochiq teriga zarar bermaslik uchun yong'inni o'chirishda kiygan kimyoviy tolali kiyimni yechmang.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1183, text: "Avtomobilning elektr jihozlari yoki benzin yonib ketsa, uni o'chirish uchun suvdan foydalanishingiz mumkin.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1184, text: "Dvigatel yonib ketganda, siz dvigatelni tezda o'chirishingiz va yong'inni o'chirish uchun kaputni ochishingiz kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1185, text: "Murakkab ob-havo sharoitida faralarni yoqib, signalni uzluksiz bosishingiz kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1186, text: "Dvigatelni yoqishdan oldin dvigatel sovutish suvini tekshiring.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1187, text: "Operatsiya tugagandan so'ng, vosita o'chirilishi, quvvatni uzib qo'yish va avtomobil eshiklarini qulflash kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1188, text: "Avtomobil tezligi oshishi bilan xavfsiz masofa qisqarishi kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1189, text: "Yo'lda harakatlanayotganda, xavfsiz masofani tezlik bilan o'zgartirish kerak emas.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1190, text: "Agar yo'lda ajratilgan bo'lak bo'lsa, boshqa avtotransport vositalari ushbu bo'lakdan o'tib ketish uchun foydalanishi mumkin.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1191, text: "Shikastlangan shinalarni o'z vaqtida almashtirish kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1192, text: "Haydovchi haydash paytida olddagi transport vositasidan xavfsiz masofani saqlashga e'tibor berishi kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1193, text: "Kechasi svetofor nazorati bo'lmagan chorrahadan o'tayotganda uzoq va past nurli chiroqlarni o'zgartirishga ruxsat berilmaydi.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1194, text: "Kechasi mashina haydashda va keskin burilishda quvib o'tishda siz doimo uzoq va past nurli chiroqlarni o'zgartirishingiz kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1195, text: "Agar boshqa transport vositasi signal bersa, u ham signalni signal berish orqali darhol javob berishi kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1196, text: "Avtomobil faqat og'ir yuk bilan pastga tushayotganda oyoq tormozini ishlatadi va retarderdan foydalanishga hojat yo'q.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1197, text: "Dvigatel havo filtrini almashtirishda faqat tashqi havo filtri elementi almashtiriladi.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1198, text: "Tog'-kon yo'llarida harakatlanayotganda tepalikka qiyalik 40 km/soat dan oshmasligi kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1199, text: "Avtomobil endigina ishga tushganda yoki haydash paytida siz gazni qayta-qayta bosishingiz mumkin.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1200, text: "Yonuvchan va portlovchi buyumlarni tashish uchun samosvallardan foydalanish mumkin.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },

  // Additional Safety (1201+)
  { id: 1201, text: "Xavfsizlik kamarlarining xizmat qilish muddati odatda 3 yildan 5 yilgacha. ( ) yil foydalanishdan keyin ular bir marta tekshirilishi kerak.", type: 'single', options: { A: "1", B: "2", C: "3" }, correct: "B" },
  { id: 1202, text: "Xuddi shu xonada yoki bir xil maydonda turli xil narsalar ma'lum masofa bilan ajratiladi va ( ) saqlashga tegishli...", type: 'single', options: { A: "alohida", B: "izolyatsiya", C: "alohida" }, correct: "B" },
  { id: 1203, text: "Korxonalar fabrikalarda xavfsiz ishlab chiqarish uchun asosiy mas'uliyatni o'z zimmalariga olishlari kerak. Asosiy xavf manbalarini tekshirish ( ) amalga oshirilgandan so'ng...", type: 'single', options: { A: "Aniqlash va baholash", B: "Baholash va hisobot berish", C: "Oldini olish va hisobot berish" }, correct: "A" },
  { id: 1204, text: "Mexanik xavfsizlik choralariga himoya vositalari... kiradi. Himoya vositalari bo'lmaganlar ( ).", type: 'single', options: { A: "Qulflash moslamasi", B: "faol qurilma", C: "qattiq qurilma" }, correct: "A" },
  { id: 1205, text: "Mashinaning xavfli qismlarini loyihalashda erishish mumkin bo'lmagan joylarga joylashtirish amaliyoti ( ) texnologiyasiga tegishli.", type: 'single', options: { A: "Nosozlik xavfsizligi", B: "Joylashuv xavfsizligi", C: "Mashina xavfsizligini himoya qilish" }, correct: "B" },
  { id: 1210, text: "\"Chang yig'uvchini tekshirish va texnik xizmat ko'rsatishda... ( ) tasdiqlanishi kerak.\"", type: 'single', options: { A: "Elektr ta'minoti, havo manbai", B: "kalit, havo trubkasi", C: "havo kaliti, lyuk eshigi" }, correct: "A" },
  { id: 1212, text: "Ikki kishi bolg'a urayotganda, ular ( ), bolg'ani silkitmasliklari kerak...", type: 'single', options: { A: "Parallel turing", B: "Orqa tarfdava uzoqroq turing", C: "Yuqoriga va pastga turing" }, correct: "B" },
  { id: 1213, text: "Amaldagi narvonning yuqori qismida xavfsizlik kancasi bo'lishi kerak va narvon oyoqlari ( ) bilan jihozlangan bo'lishi kerak.", type: 'single', options: { A: "Sirpanishga qarshi qurilma", B: "Ixtisoslashgan eskalator", C: "Izolyatsiya moslamasi" }, correct: "A" },
  { id: 1216, text: "Qo'l chiroqlari CO to'plangan joylar... Yoritish kuchlanishi ( )V dan oshmasligi kerak.", type: 'single', options: { A: "12", B: "36", C: "220" }, correct: "A" },
  { id: 1217, text: "Balandlikda ishlaganda xavfsizlik kamarini ( ), besh nuqtali ikki kancali xavfsizlik kamarini va himoya dubulg'asini to'g'ri taqish kerak.", type: 'single', options: { A: "Xavfsizlik kamari", B: "Xavfsiz arqon", C: "Qutqaruv chizig'i" }, correct: "B" },
  { id: 1218, text: "Operatsiya tugagandan so'ng, loyiha rahbari... biron bir ( ) va materiallarning uskunada qoldirilganligini tekshirishi kerak.", type: 'single', options: { A: "Asboblar", B: "Xavfli operatsiyalar", C: "Elektr ehtiyot qismlari" }, correct: "A" },
  { id: 1219, text: "Qopqoqlar, panjaralar... o'rnatilishi kerak ( ) va ish tugagandan so'ng normal holatga keltirilishi kerak.", type: 'single', options: { A: "Maxsus parvarish", B: "kordon", C: "vaqtinchalik ogohlantirish belgilari" }, correct: "C" },
  { id: 1221, text: "Yomg'ir yog'ganda ( ) ochiq havo yostig'i chang yig'ish ishining yuqori qopqog'ini oching...", type: 'single', options: { A: "OK", B: "Qat'iy taqiqlangan", C: "Rejalashtirilgan" }, correct: "B" },
  { id: 1222, text: "Xalta chang yig'uvchining lyuk eshigini ochganda, odamlarga shikast etkazmaslik uchun ehtiyot bo'ling. ( )", type: 'single', options: { A: "Materialning qulashi", B: "Balandlikdan tushish", C: "Ob'ektning zarbasi" }, correct: "A" },
  { id: 1223, text: "Kul idishi kul bilan to'sib qo'yilganda... kirish eshigini oching.", type: 'single', options: { A: "Ha", B: "Qat'iy taqiqlangan", C: "Ha, nazorat bilan" }, correct: "B" },
  { id: 1224, text: "Ta'mirlash ishlari tugallangandan so'ng... ( ) qat'iyan man etiladi.", type: 'single', options: { A: "Ko'r-ko'rona ish", B: "Ko'p kishilik ish", C: "Balandlikdan narsalarni uloqtirish" }, correct: "C" },
  { id: 1226, text: "Quvurlar toza va silliq bo'lishini ta'minlash uchun... Agar yog'ning oqishi aniqlansa, darhol ( ) yoki yong'inni o'chirish uchun favqulodda rejalar tuzing.", type: 'single', options: { A: "Yashirin xavf-xatarlarni yo'q qiling", B: "Yog 'oqishi", C: "Hisobot" }, correct: "A" },
  { id: 1241, text: "Ko'taruvchining burilish radiusidagi odamlar tezda o'tib ketishi mumkin.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1242, text: "Qaytaruvchi aravalarni, tırmıklarni va boshqa jihozlarni tekshirganda, panjaralardan ushlab turing...", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1243, text: "Tasma ostida to'plangan materialni... tozalashda asboblardan to'g'ri foydalaning.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1244, text: "Buzilgan himoya vositalarini tiklash kerak emas.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1245, text: "Mehnatni muhofaza qilish vositalarini to'g'ri kiymagan xodimlarning ishlab chiqarish maydonchasiga kirishi qat'iyan man etiladi.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1246, text: "Yukni tushirish portida katta bo'laklar... mashinani o'chirish, \"qulflash\" belgisini qo'yish va markaziy boshqaruv operatoriga murojaat qilish kerak.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "A" },
  { id: 1248, text: "Tasmali konveyer ishga tusha olmasa... muammoni hal qilish uchun pedallar, qo'l tortish yoki bosim ustunlaridan foydalaning.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
  { id: 1250, text: "Kechasi, lenta konveyer ostida to'plangan materialni tozalash uchun ikkidan ortiq kishi talab qilinadi.", type: 'boolean', options: { A: "To'g'ri", B: "Noto'g'ri" }, correct: "B" },
];

// Combine Questions
const allQuestions = [...rawStandardQuestions, ...rawAzimxonQuestions, ...rawIslomboyQuestions];

export const QUESTIONS: Question[] = allQuestions.map((q) => ({
  id: q.id,
  text: q.text,
  type: q.type as any,
  options: q.options,
  correctAnswer: q.correct,
}));

export const SECTIONS: Section[] = [
  // --- Standard Sections ---
  { id: 1, name: "Mehnat Muhofazasi Asoslari", startId: 3, endId: 30, totalQuestions: 28, category: 'standard' },
  { id: 2, name: "Favqulodda Vaziyatlar", startId: 31, endId: 60, totalQuestions: 30, category: 'standard' },
  { id: 3, name: "Yonish va Yong'in Xavfsizligi", startId: 61, endId: 90, totalQuestions: 30, category: 'standard' },
  { id: 4, name: "Birinchi Yordam (1-Qism)", startId: 91, endId: 120, totalQuestions: 30, category: 'standard' },
  { id: 5, name: "Xavfsizlik Qoidalari (T/N)", startId: 121, endId: 150, totalQuestions: 30, category: 'standard' },
  { id: 6, name: "Yong'in Xavfsizligi (T/N)", startId: 151, endId: 180, totalQuestions: 30, category: 'standard' },
  { id: 7, name: "Qoidabuzarliklar va Jarimalar", startId: 181, endId: 201, totalQuestions: 21, category: 'standard' },
  { id: 8, name: "UMUMIY IMTIHON (Random 30)", startId: 3, endId: 201, totalQuestions: 30, category: 'standard' },

  // --- Azimxon Mode Sections (A-Class Violations) ---
  { id: 101, name: "A Toifa Qoidabuzarliklar", startId: 301, endId: 309, totalQuestions: 9, category: 'azimxon' },
  { id: 102, name: "B Toifa Qoidabuzarliklar", startId: 310, endId: 326, totalQuestions: 17, category: 'azimxon' },
  { id: 103, name: "C Toifa Qoidabuzarliklar", startId: 327, endId: 345, totalQuestions: 19, category: 'azimxon' },
  { id: 104, name: "D Toifa Qoidabuzarliklar", startId: 346, endId: 357, totalQuestions: 12, category: 'azimxon' },
  { id: 105, name: "KATTA IMTIHON (Barcha 57 ta savol)", startId: 301, endId: 357, totalQuestions: 57, category: 'azimxon' },

  // --- Islomboy Mode Sections ---
  { id: 201, name: "Umumiy Xavfsizlik Qoidalari", startId: 1001, endId: 1050, totalQuestions: 50, category: 'islomboy' },
  { id: 202, name: "Yong'in va Birinchi Yordam", startId: 1061, endId: 1090, totalQuestions: 30, category: 'islomboy' },
  { id: 203, name: "Transport va Yo'l Harakati", startId: 1165, endId: 1181, totalQuestions: 17, category: 'islomboy' },
  { id: 204, name: "Texnik Xavfsizlik (T/N)", startId: 1054, endId: 1250, totalQuestions: 30, category: 'islomboy' },
  { id: 205, name: "Transport Qoidalari (T/N)", startId: 1182, endId: 1200, totalQuestions: 19, category: 'islomboy' },
  { id: 206, name: "ISLOMBOY RANDOM (30 talik)", startId: 1001, endId: 1250, totalQuestions: 30, category: 'islomboy' },
];
