
import { Question, Section } from './types';

const rawQuestions = [
  // SECTION 1: 1-30
  { text: "Birinchi psixologik eksperimental laboratoriya dunyoning qaysi mamlakati va shahrida ochilgan?", a: "Germaniya, Leybsig", b: "AQSH, Nyu York", c: "Rossiya, Moskva", d: "O‘zbekiston, Toshkent", correct: "A" },
  { text: "Tajriba(eksperiment) metodi, o‘z navbatida tabiiy va laboratoriya metodlariga ajratildi. Ushbu metodlarning ilmiy asoslari qachon va qaysi olim tomonidan ta’riflangan?", a: "1910 yilda, A.F.Lazurskiy", b: "1879 yilda, V.M.Vundt", c: "1990 yilda, E.G‘oziyev", d: "eramizdan avvalgi V asr, Arximed", correct: "A" },
  { text: "Qaysi olim tugʻma gʻoyalar tushunchasini rad etadi?", a: "Jon Lok", b: "Charlz Darvin", c: "Velgelm Vundt", d: "Zigmund Freyd", correct: "A" },
  { text: "Eng mashhur gʻoyasi – bu “tabiiy tanlanish gʻoyasi boʻlgan hamda bu evolyutsiya gʻoyasi nafaqat biologiya, balki, psixologiyaning ham prinsipiga aylangan” olim kim?", a: "Charlz Darvin", b: "Zigmund Freyd", c: "Jan Piaje", d: "Uilyam Djeyms", correct: "A" },
  { text: "Mashhur Avstriyalik shifokor, psixoanaliz asoschisi kim?", a: "Zigmund Freyd", b: "Velgelm Vundt", c: "Uilyam Djeyms", d: "Jan Piaje", correct: "A" },
  { text: "Birinchi rus fiziologi kim?", a: "I.P.Pavlov", b: "I.V.Platonov", c: "A.A.Petrovskiy", d: "N.A.Ribnikov", correct: "A" },
  { text: "Qaysi olim introspeksiyani rad etib, psixologiyani xatti-harakatni kuzatuvchi fan deb atadi?", a: "amerikalik psixolog J.B.Uotson", b: "fiziolog va faylasuf V.Vundt", c: "ingliz olimi Gobbs", d: "bolalar psixologi J.Piaje", correct: "A" },
  { text: "Zamonaviy psixologiyada faol qo‘llaniladigan quyidagi terminlar, qaysi turkumga tegishli. Jumladan, bixevioristik, xulq-genetikasi, kognitiv, sotsio-madaniy, biologik ................lar mavjud.", a: "yondashuvlar", b: "metodlar", c: "psixologiyaning fan sohalari", d: "testlar", correct: "A" },
  { text: "Biologik yondashuvning tadqiqot predmeti nimadan iborat?", a: "fiziologik jarayonlar asosida emotsiya, xotira, sensor tajribaning paydo boʻlishi", b: "kuzatuv orqali bilimga ega boʻlish", c: "ma’lumotga ishlov berish, saqlash va qayta ishlab chiqish", d: "genlarning va atrof-muhitning individual farqlanishga ta’siri", correct: "A" },
  { text: "Xulq-genetikasi nazariyasining tadqiqot predmeti nimadan iborat?", a: "genlarning va atrof-muhitning individual farqlanishga ta’siri", b: "genlarning ta’siri yo‘qligini asoslash", c: "muayyan hayotiy vaziyat va madaniy an’analarga xulq-atvor va fikrlashning bogʻliqligi", d: "fiziologik jarayonlar asosida emotsiya, xotira, sensor tajribaning paydo boʻlishi", correct: "A" },
  { text: "Psixikani o‘rganish metodlarini to‘rt guruhga ajratib, ularni tashkiliy, emperik(amaliy), natijalarni qayta ishlash va statistik natijalarni sharhlash metodlari deb nomlagan olim kim?", a: "B.G.Ananev", b: "Z.Freyd", c: "L.S.Vigotskiy", d: "J.Piaje", correct: "A" },
  { text: "Kognitiv yondashuvning tadqiqot predmet…………………………….dan iborat.", a: "ma’lumotga ishlov berish, saqlash va qayta ishlab chiqish", b: "fiziologik jarayonlar asosida emotsiya, xotira, sensor tajribaning paydo boʻlishi", c: "genlarning va atrof-muhitning individual farqlanishga ta’siri", d: "muayyan hayotiy vaziyat va madaniy an’analarga xulq-atvor va fikrlashning bogʻliqligi", correct: "A" },
  { text: "Sotsio-madaniy yondashuvning tadqiqot predmeti - ………………………. iborat.", a: "muayyan hayotiy vaziyat va madaniy an’analarga xulq-atvor va fikrlashning bogʻliqligidan", b: "ma’lumotga ishlov berish, saqlash va qayta ishlab chiqishdan", c: "genlarning va atrof-muhitning individual farqlanishga ta’siridan", d: "kuzatuv orqali bilimga ega boʻlishdan", correct: "A" },
  { text: "Inson nerv sistemasi qanday tuzilgan?", a: "markaziy, perevferik, vegatativ nerv sistemalaridan", b: "katta yarim sharlardan", c: "psixik jarayonlardan", d: "shartli va shartsiz reflekslardan", correct: "A" },
  { text: "“Bu yoʻnalish psixologiyada 8bundan 2000 yil oldin paydo boʻlgan. Inson hayotidagi barcha narsalar tushunchasi, tushunarsiz hodisalarni jon, ruh bilan bogʻlab tushuntirishga harakat qilganlar” - psixologiya fanining rivojlanish bosqichi?", a: "jon haqidagi fan sifatida rivojlanish bosqichi", b: "psixikaning mexanizmlari oʻrganuvchi fan", c: "ong haqidagi fan sifatida rivojlanish bosqichi", d: "xulq-atvor haqidagi fan sifatida rivojlanish bosqichi", correct: "A" },
  { text: "“XVII asrda tabiiy fanlar rivojlanishi bilan boshlanadi. Fikrlash, xohlash, his qilish, qobiliyatini ong deb atashgan.” - psixologiya fanining rivojlanish bosqichi?", a: "ong haqidagi fan sifatida rivojlanish bosqichi", b: "jon haqidagi fan sifatida rivojlanish bosqichi", c: "xulq-atvor haqidagi fan sifatida rivojlanish bosqichi", d: "psixikaning mexanizmlari oʻrganuvchi fan", correct: "A" },
  { text: "“XX asrdan boshlanadi. Psixologiyaning vazifasi koʻrgan narsalarni bevosita kuzatish, aniqrogʻi inson xulq-atvorini kuzatish deb hisoblangan.” - psixologiya fanining rivojlanish bosqichi?", a: "xulq-atvor haqidagi fan sifatida rivojlanish bosqichi", b: "psixikaning mexanizmlari oʻrganuvchi fan", c: "ong haqidagi fan sifatida rivojlanish bosqichi", d: "jon haqidagi fan sifatida rivojlanish bosqichi", correct: "A" },
  { text: "“Dunyoga materialistik nuqtai-nazardan qarash shakllangan. Rossiya psixologiyasining asosida aks ettirish nazariyasi koʻrsatiladi” - psixologiya fanining rivojlanish bosqichi?", a: "psixikaning mexanizmlari, qonuniyatlari va faktlarini oʻrganuvchi fan sifatida rivojlanish bosqichi", b: "xulq-atvor haqidagi fan sifatida rivojlanish bosqichi", c: "ong haqidagi fan sifatida rivojlanish bosqichi", d: "jon haqidagi fan sifatida rivojlanish bosqichi", correct: "A" },
  { text: "“Bizning miyamiz domiga tortadigan hech narsa yoʻq, bizning miyamiz butun kosmosdagi eng murakkab fizik obyekt.” – fikr muallifini toping.", a: "astronom O.Gingerich", b: "amerikalik psixolog J.Uotson", c: "fiziolog V.Vundt", d: "bolalar psixologi J.Piaje", correct: "A" },
  { text: "“Psixologiya - bu savol soʻrash va javob berishdan farqli oʻlaroq bir butun kashfiyotlar yigʻindisidir” – bu ta’rif kim tomonidan berilgan?", a: "amerikalik psixolog D.Mayers", b: "amerikalik psixolog J.Uotson", c: "amerikalik faylasuf D.Jeymes", d: "rus psixologi I.Pavlov", correct: "A" },
  { text: "Shaxsga rasmlar, testlar, grafik chizmalarni tanlash, chizishni taklif etish orqali uning psixologik xususiyatlarini bilishga qaratilgan metodlar guruhi?", a: "proektiv", b: "kreativ", c: "standartlashtirilgan kuzatuv", d: "temantik apperseptiv", correct: "A" },
  { text: "Tashqi kuzatuv qanday usul hisoblanadi?", a: "kuzatiluvchi xulq-atvorini bevosita tashqaridan turib, kuzatish orqali ma’lumotlar toʻplash usuli", b: "odamning o‘zini o‘rganishi", c: "laboratoriyada kuzatish", d: "biror ijtimoiy hodisani o‘rganish", correct: "A" },
  { text: "Introspeksiya qanday usul?", a: "odamning oʻzida kechayotgan biror oʻzgarish yoki hodisani shaxsan oʻrganishi maqsadida ma’lumotlar toʻplash va qayd etish usuli", b: "guruhiy jarayonlarni o‘rganish", c: "ijtimoiy hodisani o‘rganish", d: "maxsus dastur doirasida kuzatuv", correct: "A" },
  { text: "Psixologiya nimani о‘rgatadi?", a: "psixikani, psixik faktlarni, uning qonuniyatlari va mexanizmlarini о‘rganadi", b: "ruhni о‘rganadi", c: "nerv sistemasi tarixini", d: "faqat hodisalar bog‘liqligini", correct: "A" },
  { text: "Psixika bu – …………………………………………………… hisoblanadi.", a: "yuksak darajada tashkil topgan materiyaning alohida xossasi bo‘lib, obyektiv olamni subyektiv aks ettirish", b: "faqat hayvonlarga xos", c: "nerv sistemasi tuzilishi", d: "faollikka undovchi kuch", correct: "A" },
  { text: "Inson psixikasini necha bosqichda o‘rganish mumkin?", a: "filogenetik va ontogenetik bosqichda o‘rganish mumkin", b: "faqat bir bosqichda", c: "to‘liq o‘rganib bo‘lmaydi", d: "faqat biologik bosqichda", correct: "A" },
  { text: "................... - yuksak darajada tashkil topgan materiyaning hossasi bo‘lib, borliqni subyektiv aks ettirishdan iborat.", a: "psixika", b: "faoliyat", c: "ong", d: "xulq-atvor", correct: "A" },
  { text: "Psixika namoyon bo‘lish shakllarini belgilang.", a: "psixik jarayonlar, psixik holatlar va individual xususiyatlar", b: "instinkt, individual harakat", c: "shaxs va uning faoliyat", d: "determinizm, dualizm", correct: "A" },
  { text: "Determinizm prinsipiga ta’rif bering.", a: "psixika yashash sharoiti bilan belgilanadi va tashqi sharoitlarning o‘zgarishi bilan o‘zgarib boradi", b: "ong va faoliyat ajralmasligi", c: "ong faoliyatni belgilashi", d: "rivojlanish jarayoni", correct: "A" },
  { text: "Ongning asosiy xarakteristikasi nimadan iborat?", a: "anglash subyekti bilan obyekti о‘rtasidagi farqni ifodalash maqsadini kо‘zlash, faoliyatini ta’minlash", b: "anglash jarayoni", c: "voqelikni individual aks ettirish", d: "voqelikni alohida aks ettirish", correct: "A" },

  // SECTION 2: 31-60
  { text: "Oliy nerv faoliyatining tiplari ya’ni temperamentlarni aniqlashda asosiy xususiyatlarni belgilang.", a: "qо‘zg‘alish va tormozlanish, muvozanat(labil va stabil)", b: "shartli reflekslar", c: "nerv hujayralari bo‘linishi", d: "optimal qo‘zgalish o‘choqlari", correct: "A" },
  { text: "Hayvonlarning asosiy harakat formalari qanday ataladi?", a: "instinkt", b: "tropizm", c: "ko‘nikma", d: "refleks", correct: "A" },
  { text: "Qanday refleks turlari mavjud?", a: "shartli va shartsiz", b: "shartli va orttirilgan", c: "tug‘ma va individual", d: "orttirilgan va individual", correct: "A" },
  { text: "Faoliyat nima?", a: "anglangan maqsad bilan boshqariladigan tashqi (jismoniy) va ichki (psixik) faoliyatlarning yig‘indisi", b: "bilishga bo‘lgan ehtiyoj", c: "maqsadlar mazmuni", d: "ko‘nikmalarning malakaga aylanishi", correct: "A" },
  { text: "Ko‘nikma nima?", a: "faoliyatdagi ish-harakatlarni o‘zlashtirish jarayoni", b: "tug‘ma reflekslar", c: "instinktiv harakatlar", d: "avtomatlashgan harakatlar", correct: "A" },
  { text: "Shaxsni o‘rab turgan tashqi muhitni o‘zgartirishga qaratilgan faollik qanday?", a: "tashqi faollik", b: "ichki faollik", c: "perseptiv faoliyat", d: "fikrlash faoliyati", correct: "A" },
  { text: "Faoliyatning qaysi turi birlamchi o‘zlashtirish manbai hisoblanadi?", a: "mehnat va o‘yin", b: "ijodiy ish", c: "ishlab chiqarish", d: "qiziqish", correct: "A" },
  { text: "Qanday omillar ko‘nikmalarni yuzaga keltiruvchi omil hisoblanadi?", a: "takrorlash, mashq harakatlari", b: "kuchli qo‘zg‘alish", c: "bir xil yo‘nalish", d: "o‘zaro raqobat", correct: "A" },
  { text: "Ong va faoliyatning birligi deganda ……………………………… tushuniladi.", a: "ong va faoliyat bir-biriga qarama-qarshi ham emas, o‘xshash ham emas, ammo ular bir-birini taqozo qilishi", b: "ong mazmunni belgilamasligi", c: "ongning namoyon bo‘lishi", d: "ongning rivojlanishi", correct: "A" },
  { text: "Tashqi faoliyat asosida ichki psixik jarayonlarga o‘tish ro‘y bersa qanday jarayon?", a: "interiorizatsiya", b: "eksteriorizatsiya", c: "fikrlash faoliyati", d: "imajitiv faoliyat", correct: "A" },
  { text: "Malaka bu – …………………………………………………… hisoblanadi.", a: "ish – harakatlarni avtomatlashishi", b: "ko‘nikmaning paydo bo‘lishi", c: "ish – harakatlarni o‘zlashtirish jarayonidir", d: "ichki faollik", correct: "A" },
  { text: "Ongimizda shakllangan g‘oyalarni bevosita tashqi harakatlarda namoyon bo‘lishi nima?", a: "eksteriorizatsiya", b: "fikrlash faoliyati", c: "interiorizatsiya", d: "imajitiv faoliyat", correct: "A" },
  { text: "Shaxsning o‘zi, o‘z imkoniyatlari haqidagi umumlashgan tasavvurlari?", a: "o‘z-o‘ziga baho", b: "“U” obrazi", c: "shaxsning ustanovkalari", d: "dunyoqarashi", correct: "A" },
  { text: "Shaxs taraqqiyotini harakatga keltiruvchi kuchlarni aniqlang.", a: "ijtimoiy muhit, ta’lim-tarbiya va faoliyatdagi insonning faolligi", b: "ijtimoiy munosabat", c: "o‘zaro munosabatlar", d: "ijodiy faoliyatda faollik", correct: "A" },
  { text: "Individuallik – bu …………………………………… hisoblanadi.", a: "ayrim psixologik xususiyatlarning har bir shaxs uchun o‘ziga xos bo‘lgan betakror birikmasi", b: "shaxsning tajribasi", c: "chaqaloq rivojlanishi", d: "egizaklarning o‘xshashligi", correct: "A" },
  { text: "Shaxs tushunchasini izohlovchi eng to‘liq ta’rifni aniqlang.", a: "jamiyat a’zosi sifatida, odamlar bilan munosabatda bo‘ladigan, ongli, konkret bir inson", b: "odamning sut emizuvchiligi", c: "ijtimoiy tajriba o‘zlashtirilishi", d: "o‘z-o‘zini anglaganlik", correct: "A" },
  { text: "Individ – bu…………………………………… hisoblanadi.", a: "odamning insonlik jinsiga mansubligi", b: "jamiyat a’zosi sifatida munosabatda bo‘lish", c: "psixikaning muhim xususiyatti", d: "o‘z-o‘zini anglagan odam", correct: "A" },
  { text: "Shaxs tuzilishidagi biologik omillarni aniqlang.", a: "irsiyat, bosh miya va nerv tizimi xususiyatlari", b: "oila, mahalla, maktab", c: "innovatsion o‘zgarishlar", d: "taraqqiyot qonuniyatlari", correct: "A" },
  { text: "Shaxsning o‘zi haqidagi obraz nima deb ataladi?", a: "“Men” obrazi", b: "“U” obrazi", c: "milliy o‘zlik", d: "etnos", correct: "A" },
  { text: "Psixologiyada shaxsning o‘z-o‘ziga bahosi qanday turlarga ajratilgan?", a: "past baho, real baho, yuqori baho", b: "faqat past va yuqori", c: "Id, Ego, Super Ego", d: "“Men” va “Men emas”", correct: "A" },
  { text: "Z.Freyd nazariyasida shaxsning qaysi instansiyasi “qo‘zg‘ovchilar ustidan hukmronlik qiladi”?", a: "“EGO” – “MEN”", b: "“ID” – “U”", c: "“SUPER-EGO”", d: "“SUPER-MEN”", correct: "A" },
  { text: "Qaysi olimning konsepsiyasiga ko‘ra shaxs - “U”, “Men”, “Ideal men”dan iborat?", a: "Z.Freyd", b: "A.Petrovskiy", c: "K.Levin", d: "K.Platonov", correct: "A" },
  { text: "Sezgi nima?", a: "eng oddiy psixik jarayon bo‘lib, narsa va hodisalarning o‘ziga xos xususiyatlarini ongimizda aks etishi", b: "o‘tmishdagi voqealarga munosabat", c: "esga tushirish", d: "shaxs xarakteri", correct: "A" },
  { text: "Insonning barcha sezgilari qanday turkumlarga klassifikatsiya qilinadi?", a: "ekstroseptiv, interoseptiv, proprioseptiv", b: "interaktiv, kommunikativ", c: "ekstroseptiv, perseptiv", d: "interotseptiv, perseptiv", correct: "A" },
  { text: "Ekstroseptiv sezgilarga qanday sezgilar kiradi?", a: "hid bilish, ta’m bilish, ko‘rish, eshititsh, teri tuyush", b: "organik sezgilar", c: "kinestetik sezgilar", d: "faqat ko'rish", correct: "A" },
  { text: "Interoseptiv sezgilarga qanday sezgilar kiradi?", a: "organik", b: "kinestetik", c: "perseptiv", d: "kommunikativ", correct: "A" },
  { text: "Sensibilizatsiya bu-……………………………………………………. hisoblanadi.", a: "mashq qildirilishi natijasida sezgi organlarida sezuvchanlikning ortishi", b: "sezgilarning so‘nishi", c: "ko‘z gavharini moslashishi", d: "predmetlar haqidagi ma’lumotlar", correct: "A" },
  { text: "Adaptatsiya turlarini ko‘rsating.", a: "pozitiv, negativ", b: "negativizm, kommunikativ", c: "subyektiv, obyektiv", d: "taktik, negativ", correct: "A" },
  { text: "Qorni ochlikni, chanqashni sezish qaysi sezgi turiga oid?", a: "organik", b: "to‘yish", c: "eshitish", d: "ta’m bilish", correct: "A" },
  { text: "Gavdaning fazodagi holati qaysi sezgilar orqali seziladi?", a: "statik sezgilar", b: "ekstroretseptiv sezgilar", c: "interotseptiv sezgilar", d: "nospetsifik sezgilar", correct: "A" },

  // SECTION 3: 61-90
  { text: "Idrok nima?", a: "sezgi a’zolariga bevosita ta’sir etib turgan narsa va hodisalar obrazlarining kishi ongida bir butun holda aks ettirilishi", b: "faqat alohida xususiyatlarni aks ettirish", c: "bor narsani noto‘g‘ri anglash", d: "yo‘q narsani his qilish", correct: "A" },
  { text: "Sezgi a’zolarimizga bevosita ta’sir etib turib, ongimizda bir butun aks etishiga nima deyiladi?", a: "idrok", b: "xotira", c: "xayol", d: "tafakkur", correct: "A" },
  { text: "Gallyutsinatsiya nima?", a: "yo‘q narsalarni idrok qilish", b: "shaxsning idrok qilish qobiliyati", c: "bor narsani noto‘g‘ri idrok qilish", d: "idrokning tajribaga bog‘liqligi", correct: "A" },
  { text: "Narsalarning sharoiti o‘zgarsada obrazining o‘zgarmasligi bu nima?", a: "idrok konstantaligi", b: "sezgi", c: "xotira", d: "gallyutsinatsiya", correct: "A" },
  { text: "Idrok konstantaligi - …....……………………….. deyiladi.", a: "narsalarning sharoiti o‘zgarsada, obrazining o‘zgarmasligi", b: "shaxsning idrok qilish qobiliyati", c: "idrokning tajribaga bog‘liqligi", d: "vaqtni idrok qilish", correct: "A" },
  { text: "Illyuziya nima?", a: "bor narsani noto‘g‘ri, yanglish idrok qilish", b: "bir nimani his qilib anglash", c: "shaxsning idrok qilish qobiliyati", d: "yo‘q narsani idrok qilish", correct: "A" },
  { text: "Appersepsiya nima?", a: "idrokning shaxs va uning tajribasiga bog‘liqligi", b: "o‘smirlikning o‘tish davri", c: "yo‘q narsani idrok qilish", d: "shaxsning adaptatsion davri", correct: "A" },
  { text: "Obyekt va fon - bu nima?", a: "shaxs uchun ayni paytda ahamiyatli narsa (obyekt), muhim bo‘lmagan narsa (fon)", b: "sezgi va idrok bog‘liqligi", c: "uyni batafsil idrok qilish", d: "narsalarning hajmini idrok qilish", correct: "A" },
  { text: "Konvergensiya – bu ........................ hisoblanadi.", a: "biror narsaga qaraganda ikkala ko‘z soqqasining qanshar birdan burilishi", b: "fazo munosabatini idrok qilish", c: "odatdagi narsalarni idrok qilish", d: "ko‘z pardasi", correct: "A" },
  { text: "Idrokning o‘ziga xos xususiyatilari qaysi qatorda?", a: "predmetligi, yaxlitligi, tanlanganligi, konstantligi, mantiqiyligi, strukturaliligi", b: "faqat yaxlitligi va tanlanganligi", c: "predmetligi, yaxlitligi, tanlanganligi", d: "predmetligi, yaxlitligi", correct: "A" },
  { text: "Qaysi qatorda diqqat tushunchasiga to‘liq ta’rif berilgan?", a: "ongimizning muayyan obyektga yo‘naltirilishi va unda to‘planishidan iborat psixik holat", b: "amaliy faoliyatga kiritilgan jarayon", c: "obyektga qisqa vaqt qarash", d: "ongni uzoq vaqt taqsimlanishi", correct: "A" },
  { text: "Dominanta tushunchasini fanga qaysi olim kiritgan?", a: "A.A.Uxtomiskiy", b: "A.R.Luriya", c: "I.P.Pavlov", d: "I.M.Sechenov", correct: "A" },
  { text: "Oliy nerv faoliyatidagi qo‘zg‘alish va tormozlanish o‘rtasidagi munosabat?", a: "dominanta", b: "nerv jarayonlarining induksiyasi", c: "parishonxotirlik", d: "retikulyar formatsiya", correct: "A" },
  { text: "Diqqatning nerv fiziologik asosi qaysi olimlar tomonidan o‘rganilgan?", a: "I.P.Pavlov, A.A.Uxtomiskiy", b: "A.A.Uxtomiskiy, I.M.Sechenov", c: "Z.Freyd, I.M.Sechenov", d: "Vigotskiy, A.R.Luriya", correct: "A" },
  { text: "I.P.Pavlovning ta’kidlashicha diqqatning nerv fiziologik asosini ……………. tashkil qiladi.", a: "“bu nima?” refleksi", b: "shartli reflekslar", c: "shartsiz reflekslar", d: "nerv jarayonlarining induksiyasi", correct: "A" },
  { text: "To‘satdan ta’sir qilgan biror sabab tufayli xohishimizdan tashqari hosil bo‘ladigan diqqat?", a: "ixiyorsiz diqqat", b: "ixtiyordan so‘nggi diqqat", c: "parishonxotirlik", d: "ixtiyoriy diqqat", correct: "A" },
  { text: "…………………. deb, oldindan belgilangan maqsad asosida ongli ravishda qaratilgan diqqatga aytiladi.", a: "ixtiyoriy diqqat", b: "ixiyorsiz diqqat", c: "ixtiyoriydan keyingi diqqat", d: "parishonxotirlik", correct: "A" },
  { text: "Ixtiyoriy diqqatning nerv fiziologik asosini ……………. tashkil qiladi.", a: "miya yarim sharlarining po‘stida vujudga keladigan optimal qo‘zg‘alish", b: "o‘ng yarim shar", c: "ikkinchi signallar sistemasi", d: "shartsiz va shartli reflekslar", correct: "A" },
  { text: "………………………….. deb, odam o‘z diqqatini uzoq muddat davomida muttasil qaratib tura olishiga aytiladi.", a: "diqqatning kuchi va barqarorligi", b: "diqqatning ko‘lami", c: "diqqatning bo‘linuvchanligi", d: "diqqatning turi", correct: "A" },
  { text: "Diqqatning kuchli va barqaror bo‘lishi ko‘proq …………………. bog‘liq.", a: "diqqatimiz qaratilgan narsaning xususiyatlari, ahamiyati va shu narsa bilan amalga oshiriladigan faoliyatimizga", b: "faqat obyekt ahamiyatiga", c: "nerv sistemasining xususiyatlariga", d: "odamning ayni chog‘dagi holatiga", correct: "A" },
  { text: "……………………. - ayni bir vaqtda odamning idrokiga sig‘ishi mumkin bo‘lgan narsalar miqdori.", a: "diqqatning ko‘lami", b: "diqqatning bo‘linuvchanligi", c: "diqqatning konsentratsiyasi", d: "diqqatning kuchi va barqarorligi", correct: "A" },
  { text: "Diqqatning ko‘lami qaysi asbob yordamida o‘lchanadi?", a: "taxistoskop", b: "manometr", c: "sekundametr", d: "varometr", correct: "A" },
  { text: "………………….. - ayni bir vaqtda diqqatmizning ikki-uch narsaga qaratilishiga aytiladi.", a: "diqqatning bo‘linuvchanligi", b: "diqqatning konsentratsiyasi", c: "diqqatning kuchi va barqarorligi", d: "diqqatning ko‘lami", correct: "A" },
  { text: "Agar diqqatimiz ayni bir vaqtda bir necha narsaga qaratilgan bo‘lsa bu -…………………….", a: "diqqatning taqsimlanganligi", b: "diqqatning ko‘lami", c: "diqqatning konsentratsiyasi", d: "diqqatning kuchi va barqarorligi", correct: "A" },
  { text: "Qaysi qatorda diqqat tushunchasiga to‘g‘ri tarif berilgan?", a: "ongimizning muayyan obyektga yo‘naltirilishi va unda to‘planishidan iborat psixik holat", b: "diqqatning taqsimlanmasligi", c: "faoliyatga kiritilganlik", d: "faqat tashqi ta'sir", correct: "A" },
  { text: "Dominanta tushunchasini fanga kiritgan olim?", a: "A.A.Uxtomiskiy", b: "A.R.Luriya", c: "I.P.Pavlov", d: "I.M.Sechenov", correct: "A" },
  { text: "Qaysi qatorda xotira tushunchasiga to‘g‘ri ta’rif berilgan?", a: "ilgari idrok qilgan, boshdan kechirgan va bajargan ishlarimizni yodda olib qolish, saqlash, unutish va qayta esga tushirishdan iborat psixik jarayon", b: "faqat esda saqlash", c: "kundalik bilimlar yig‘indisi", d: "faqat unutish jarayoni", correct: "A" },
  { text: "Qaysi qatorda xotira jarayonlari ko‘rsatilgan?", a: "esda olib qolish, esda saqlash, unutish, qayta esga tushirish", b: "esda olib qolish va saqlash", c: "saqlash, esga tushirish, unutish", d: "faqat esda olib qolish", correct: "A" },
  { text: "Qaysi qatorda assotsiatsiya tushunchasiga to‘g‘ri ta’rif berilgan?", a: "xotiramizda mustahkamlangan va ongimizda qayd qilingan ayrim voqea-hodisalarning o‘zaro muvaqqat bog‘lanishidir, bunda biror buyumni esda olib qolish uni boshqa buyumlar bilan bog‘lash orqali amalga oshiriladi", b: "miyada iz hosil bo‘lishi", c: "material izini yo‘qolishi", d: "esda qoldirish tezligi", correct: "A" },
  { text: "«Muvaqqat nerv bog‘lanishlari hayvonot olamida va bizning o‘zimizga ham bo‘ladigan eng umumiy fiziologik hodisadir.» Mazkur fikr muallifi?", a: "I.Pavlov", b: "I.Sechenov", c: "L.Vigotskiy", d: "A.Smirnov", correct: "A" },

  // SECTION 4: 91-120
  { text: "Qaysi qatorda psixik faollik tabiatiga ko‘ra xotira turlari berilgan?", a: "harakat, hissiy, obrazli, so‘z-mantiq, mexanik xotira", b: "ixtiyorsiz, ixtiyoriy", c: "qisqa va uzoq muddatli", d: "operativ xotira", correct: "A" },
  { text: "Muddatiga ko‘ra xotira turlari qaysi qatorda ko‘rsatilgan?", a: "qisqa muddatli va uzoq muddatli, operativ", b: "ixtiyorsiz va ixtiyoriy", c: "harakat va hissiy", d: "mexanik va mantiqiy", correct: "A" },
  { text: "Turli xil harakatni esda olish va qayta esga tushirishdan iborat xotira?", a: "harakat xotirasi", b: "hissiy xotira", c: "obrazli xotira", d: "ixtiyorsiz xotira", correct: "A" },
  { text: "Tovush, hidlar, ta’mlar bilan bog‘liq xotira nima?", a: "obrazli xotira", b: "obyektiv xotira", c: "hissiy xotira", d: "taktil sezgi", correct: "A" },
  { text: "Idrok qilingan narsa obrazlarining miya po‘stida iz hosil qilishi nima?", a: "esda saqlash", b: "esga tushirish", c: "unutish", d: "sinesteziya", correct: "A" },
  { text: "Ixtiyoriy esda olib qoldirishda qanday usullardan foydalaniladi?", a: "maqsad qo‘yish, o‘quv materialini tushunib esda qoldirish, esda qoldirishning ratsional usullari", b: "faqat takrorlash", c: "tasodifiy usullar", d: "majburlash", correct: "A" },
  { text: "Beixtiyor esda qoldirishda qaysi jarayon asosiy rol o‘ynaydi?", a: "qiziqish", b: "tajriba", c: "shakl va hajmi", d: "dunyoqarash", correct: "A" },
  { text: "O‘tmishda idrok qilingan narsalarning ongimizda qayta tiklanishi?", a: "esga tushirish", b: "xotira mukammaligi", c: "esnash", d: "unutish", correct: "A" },
  { text: "Ilgari idrok qilingan obrazlarining ongimizda qaytadan gavdalanishi?", a: "xotira tasavvurlar", b: "esda saqlash", c: "xayol tasavvurlari", d: "unutish", correct: "A" },
  { text: ".................. - narsa hodisalarning asosiy qonuniyatlarini tafakkurimizda aks ettirilishidir.", a: "tafakkur", b: "tafakkur mustahkamligi", c: "tafakkur operatsiyalari", d: "tafakkur shakllari", correct: "A" },
  { text: "................- narsa va hodisalarni fikran qismlarga ajratib tahlil qilish operatsiyasi.", a: "analiz", b: "sintez", c: "taqqoslash", d: "klassifikatsiya", correct: "A" },
  { text: "................- ajralgan ayrim qismlarni fikran birlashtirib butun holga keltirish operatsiyasi.", a: "sintez", b: "analiz", c: "taqqoslash", d: "klassifikatsiya", correct: "A" },
  { text: "................- narsa va hodisalarning bir-biriga o‘xshashligi va farqini aniqlash operatsiyasi.", a: "taqqoslash", b: "sintez", c: "analiz", d: "klassifikatsiya", correct: "A" },
  { text: "Narsa va hodisalarning xususiyatlari haqida tasdiqlab yoki inkor qilib aytilgan fikr?", a: "hukm", b: "xulosa chiqarish", c: "tushuncha", d: "konkret tushuncha", correct: "A" },
  { text: "Umumlashtirish – bu ……………………………………… hisoblanadi.", a: "tafakkurda aks etgan bir turkum narsalarning, o‘xshash muhim belgilarning shu narsalar to‘g‘risidagi bitta tushuncha qilib, fikrda birlashtirish", b: "ikkinchi darajali belgilarni ajratish", c: "farqlarni aniqlash", d: "qismlarga bo‘lish", correct: "A" },
  { text: "Abstraktsiya (mavhumlashtirish) - bu ..................................... hisoblanadi.", a: "moddiy dunyodagi narsa va hodisalarning muhim xususiyatlarini farqlab olib, ana shu xususiyatlarning muhim bo‘lmagan ikkinchi darajali xususiyatlarini fikran ajratib olish", b: "bitta tushunchada birlashtirish", c: "farqini aniqlash", d: "tahlil qilish", correct: "A" },
  { text: "Klassifikatsiyalash - bu ..................................... hisoblanadi.", a: "bir turkum ichidagi narsalarning bir-biriga o‘xshashligiga va boshqa turkumdagi narsalardan farq qilishiga qarab narsalarni turkumlarga ajratish tizimi", b: "birlashtirish", c: "farqni anglash", d: "xususiyatlarni tahlil qilish", correct: "A" },
  { text: "Konkretlashtirish - bu..................................... hisoblanadi.", a: "hodisalarni ichki bog‘lanish va munosabatlardan qat’iy nazar bir tomonlama ta’kidlashdan iborat fikr yuritish", b: "farqni aniqlash", c: "birlashtirish", d: "ajratish tizimi", correct: "A" },
  { text: "Ontogenezda shakliga ko‘ra tafakkur turlari rivojlanishining ketma-ketligi:", a: "ko‘rgazmali-harakat tafakkuri, ko‘rgazmali-obrazli tafakkur, mavhum tafakkur", b: "faqat mantiqiy", c: "induktiv, deduktiv", d: "hukm, xulosa", correct: "A" },
  { text: "Ontogenezda tafakkur shakllari rivojlanishining ketma-ketligi:", a: "tushuncha, hukm, xulosa chiqarish", b: "xulosa, tushuncha, hukm", c: "induktiv, deduktiv", d: "ko‘rgazmali, obrazli", correct: "A" },
  { text: "Qaysi qatorda xulosa chiqarish turlari to‘g‘ri ko‘rsatilgan?", a: "induktiv, deduktiv, analogik", b: "yakka, konkret, umumiy", c: "juz’iy, taxminiy", d: "faqat induktiv", correct: "A" },
  { text: "Ikki yoki undan ortiq hukmlardan yangi hukm hosil qilish?", a: "xulosa chiqarish", b: "tushuncha", c: "hukm", d: "mantiqiy fiklash", correct: "A" },
  { text: "Narsa va hodisalarning umumiy va muhim belgilarini aks ettiruvchi tafakkur shakli?", a: "tushuncha", b: "xulosa chiqarish", c: "hukm", d: "induktiv xulosa chiqarish", correct: "A" },
  { text: "Bevosita idrok qilinayotgan predmetlar emas, balki tasavvur qilinayotgan narsa va hodisalar haqida fikrlashdan iborat tafakkur turi?", a: "nazariy", b: "amaliy", c: "ko‘rgazmali-harakat", d: "fazoviy", correct: "A" },
  { text: "“Toshkent – O‘zbekiston Respublikasi poytaxtidir” - bu qanday hukm?", a: "yakka hukm", b: "umumiy hukm", c: "xato hukm", d: "soxta hukm", correct: "A" },
  { text: "…………..-ayrim elementlarni bitta obraz qilib qo‘shish va shularning kombinatsiyasi.", a: "agglutinatsiya", b: "aksentirovka", c: "kichraytirish", d: "kattalashtirish", correct: "A" },
  { text: "“Bosh miya yarim sharlari peshona qismining tepa tomonida so‘zlarning sensor obrazlari joylashgan”?", a: "K.Vernike", b: "P.Anoxin", c: "I.Pavlov", d: "P.Broka", correct: "A" },
  { text: "So‘zlarni idrok qilishning buzilishi, fonematik eshituvning buzilishi?", a: "sensor afaziya", b: "semantik afaziya", c: "dinamik afaziya", d: "motor afaziya", correct: "A" },
  { text: "Nutq afazisiyasini qaysi olim o‘rgangan?", a: "A.Luriya", b: "P.Broka", c: "N.Jinkin", d: "K.Verniki", correct: "A" },
  { text: "Qaysi nutq turining xususiyatlaridan biri tafakkurning mexanizmi funksiyasini bajarishdir?", a: "ichki nutq", b: "tashqi nutq", c: "og‘zaki nutq", d: "yozma nutq", correct: "A" },

  // SECTION 5: 121-150
  { text: "Tilning asosiy funksiyasi nima?", a: "kommunikatsiya", b: "faqat axborot uzatish", c: "tajriba egallash", d: "faqat aqliy rivojlanish", correct: "A" },
  { text: "Bir nechta kishilar bilan amalga oshiriladigan nutq turi?", a: "polilogik", b: "dialogik", c: "monologik", d: "yozma", correct: "A" },
  { text: "Miya po‘stining ma’lum qismi shikastlansa nutq artikulyatsiyasi buzilishini kim kashf etgan?", a: "P.Broka", b: "I.Pavlov", c: "P.Anoxin", d: "K.Vernike", correct: "A" },
  { text: "Tinglovchining nutqi esa ………… hisoblanadi.", a: "passiv", b: "faol", c: "monolog", d: "ichki", correct: "A" },
  { text: "Til yoki boshqa belgilar vositasida axborot berish nima?", a: "kommunikatsiya", b: "identifikatsiya", c: "muloqot", d: "refleksiya", correct: "A" },
  { text: "So‘zlovchining nutqi qanday nutq?", a: "faol nutq", b: "passiv nutq", c: "faqat dialog", d: "faqat ichki", correct: "A" },
  { text: "Aniq shartli belgilar orqali mantiqiy yuklamani aks ettiruvchi noverbal nutq turi?", a: "signifikatsiya", b: "mimika", c: "lakonik", d: "exologik", correct: "A" },
  { text: "Odam o‘z his-kechinmalarini nutqsiz (tana harakatlari bilan) qanday namoyon etadi?", a: "mimika, pantomimika", b: "faqat nutq", c: "dialog", d: "monolog", correct: "A" },
  { text: "Muloqot nima?", a: "kishilarning til yordamida munosabatda bo‘lishi, ma’lumotlar almashinishi jarayoni", b: "faqat mehnat faoliyati", c: "dunyoqarash shakllanishi", d: "faqat aqliy rivojlanish", correct: "A" },
  { text: "Muloqotning axborot almashinuvi tomoni nima?", a: "kommunikativ", b: "interaktiv", c: "perseptiv", d: "refleksiv", correct: "A" },
  { text: "Muloqotning bir-birlarini idrok etishlari va tushunishlari tomoni?", a: "perseptiv", b: "interaktiv", c: "kommunikativ", d: "refleksiv", correct: "A" },
  { text: "Ikki yoki undan ortiq kishilar o‘rtasidagi axborot ayriboshlash jarayoni?", a: "muloqot", b: "afaziya", c: "refleksiya", d: "kommunikatsiya", correct: "A" },
  { text: "Subyektning sherigi tomonidan qay tarzda idrok etilganligini anglab yetishi nima?", a: "refleksiya", b: "kommunikatsiya", c: "muloqot", d: "agglutinatsiya", correct: "A" },
  { text: "Empatiya bildirish deganda nima tushuniladi?", a: "hamdardlikni namoyish etish", b: "faqat idrok etish", c: "g‘azab namoyon etish", d: "sevgi izhori", correct: "A" },
  { text: "Ongsizlik taʼlimotining asoschisi kim?", a: "Z.Freyd", b: "V.Makdugall", c: "D.Uotson", d: "K.Yung", correct: "A" },
  { text: "Biologik ehtiyojlar asosida inson motivlari yotadi degan qarash?", a: "АQSH va G‘arb psixologlari", b: "O‘zbek psixologlari", c: "Sobiq sovet psixologlari", d: "Sharq psixologlari", correct: "A" },
  { text: "Oddiy ehtiyojlar asosida ongsiz hosil bo‘ladigan ustanovkalar?", a: "elementar ustanovkalar", b: "ijtimoiy ustanovkalar", c: "bazaviy ijtimoiy ustanovkalar", d: "qadriyatlar tizimi", correct: "A" },
  { text: "Vaziyatlar taʼsirida ijtimoiy obyektlarga nisbatan shakllanadigan ustanovkalar?", a: "ijtimoiy ustanovkalar", b: "bazaviy ustanovkalar", c: "elementar ustanovkalar", d: "qadriyatlar tizimi", correct: "A" },
  { text: "Shaxsning umumiy yo‘nalishini belgilaydigan ijtimoiy ustanovkalar?", a: "bazaviy ijtimoiy ustanovkalar", b: "ustanovkalar", c: "qadriyatlar tizimi", d: "elementar ustanovkalar", correct: "A" },
  { text: "E’tiqod tushunchasining ta’rifini belgilang.", a: "shaxsning o‘z qarashlari, tamoyillari, dunyoqarashlariga mos harakat qilishga undovchi ehtiyoj, qadriyatlar tizimi", b: "faqat ehtiyoj", c: "anglanmagan motiv", d: "faqat dunyoqarash", correct: "A" },
  { text: "Faoliyat asosini tashkil qiluvchi, xatti-harakatga undovchi kuch?", a: "motiv", b: "iroda", c: "mehnat", d: "o‘yin", correct: "A" },
  { text: "Motiv rivojlanishining birinchi bosqichi (biologik ehtiyoj stimul bo‘lganda)?", a: "dastlabki(abstrakt) motivning shakllanishi", b: "tashqi qidiruvchi faollik", c: "ichki qidiruvchi faollik", d: "xohishlarni shakllantirish", correct: "A" },
  { text: "Motiv nima?", a: "kishini faoliyatga undovchi kuch, sabab va ehtiyojlarning yig‘indisi", b: "hissiyotning namoyon bo‘lishi", c: "shaxs faoliyatining maxsus turi", d: "istaklar tizimi", correct: "A" },
  { text: "Qaysi olim motivatsiya irsiy xususiyatga ega degan qarashni ilgari surgan?", a: "V.Makdugall", b: "D.Uotson", c: "E.Torndayk", d: "Z.Freyd", correct: "A" },
  { text: "Z.Freyd motivatsiya manbai sifatida “ID–U”ga qanday yondashgan?", a: "“U” tushunchasi mazmuni tug‘ma va o‘zgarmasdir", b: "o‘zgaruvchandir", c: "mantiqiy omil", d: "ortirilgan tajriba", correct: "A" },
  { text: "Motivatsiya nima?", a: "motivlarning qoida, dalil va qonuniyatlar bilan asoslanishi", b: "ongsyiz harakat", c: "faqat moyillik", d: "xatti-harakat tahlili", correct: "A" },
  { text: "Shaxs xulq-atvorini tushuntirib beruvchi psixologik sabablar majmui?", a: "motivatsiya", b: "iroda", c: "kayfiyat", d: "ruhlanish", correct: "A" },
  { text: "Hissiyotdan darak beruvchi “impressiv” so‘zining maʼnosi?", a: "ta’sirli", b: "qo‘zg‘alish", c: "so‘nish", d: "g‘azab", correct: "A" },
  { text: "Dinamik stereotiplar orqali kechadigan hissiyotlarni o‘rgangan olim?", a: "I.Pavlov", b: "Z.Freyd", c: "D.Uotson", d: "S.Ivanov", correct: "A" },
  { text: "“Zo‘riqish” qaysi so‘zining lug‘aviy maʼnosi?", a: "stress", b: "emotsiya", c: "аffekt", d: "аmbivalentlik", correct: "A" },

  // SECTION 6: 151-180
  { text: "Stressning ikki turi to‘g‘ri ko‘rsatilgan qatorni toping.", a: "pixologik, fiziologik", b: "information, estetik", c: "xushchachaq, аgressiv", d: "psixologik, pedagogik", correct: "A" },
  { text: "Аffekt nima?", a: "tez paydo bo ‘lib nihoyatda kuchli, g‘oyat jo‘shqinlik bilan o‘tadigan qisqa muddatli emotsional holat", b: "tushkunlik", c: "g‘am-alam", d: "yuqori kayfiyat", correct: "A" },
  { text: "Ruhiy jarayonlarga muayyan vaqt davomida tus berib turuvchi emotsional holat?", a: "kayfiyat", b: "stress", c: "idrok", d: "hissiy ton", correct: "A" },
  { text: "Psixologiyaga stress tushunchasini qaysi olim olib kirgan?", a: "G.Sele", b: "Z.Freyd", c: "G.Tord", d: "G.Lebon", correct: "A" },
  { text: "Irodaning qaysi sifatidan maqsadga intiluvchanlikni izohlashda foydalaniladi?", a: "tirishqoqlikdan", b: "o‘jarlikdan", c: "qaysarlikdan", d: "yalqovlikdan", correct: "A" },
  { text: "Bolada emotsional rivojlanishning eng faol davri?", a: "tug‘ilgandan 3 yoshgacha", b: "o‘smirlik", c: "maktab davri", d: "kattalik", correct: "A" },
  { text: "Hissiyot – bu ……………………………………………………… hisoblanadi.", a: "tashqi olamdagi narsa va hodisalarga nisbatan bo‘lgan munosabatlarning va undan hosil bo‘lgan ichki kechinmalarimizning ongimizda aks ettirilishi", b: "faqat psixik jarayon", c: "axloqiy hislar", d: "faqat ehtiyojlar bilan bog‘liq", correct: "A" },
  { text: "……………… - kishining bir obyektga nisbatan bir vaqtning o‘zida paydo bo‘ladigan bir-biriga qarama –qarshi emotsional irodaviy holatidir.", a: "ambivalentlik", b: "emotsional kechinma", c: "affekt", d: "dinamik stereotip", correct: "A" },
  { text: "Hissiy “ton” tushunchasining lug‘aviy maʼnosini belgilang.", a: "yunoncha “tonos” - urg‘u berish", b: "lotincha “emovere”", c: "ehtiros", d: "shijoat", correct: "A" },
  { text: "Emotsiya tushunchasining lug‘aviy maʼnosini belgilang.", a: "lotincha “emovere” - qo‘zg‘atish, hayajonlanish", b: "shijoat", c: "urg'u", d: "ranjish", correct: "A" },
  { text: "Emotsional holatlar qaysi qatorda to‘g‘ri keltirilgan?", a: "hissiy ton, kayfiyat, ehtiros, affekt, stress", b: "gumanizm, ranjish", c: "hamkorlik, sevgi", d: "xarakter, temperament", correct: "A" },
  { text: "Psixik holatlar qaysi qatorda to‘g‘ri ko'rsatilgan?", a: "hissiyot, kayfiyat, stress", b: "sezgi, idrok", c: "xarakter, qobiliyat", d: "individ, xotira", correct: "A" },
  { text: "Oliy nerv faoliyati tiplari haqidagi ta’limot kim tomonidan yaratilgan?", a: "I.Pavlov", b: "B.Teplov", c: "D.Nebilitsin", d: "A.Klimov", correct: "A" },
  { text: "Oliy nerv faoliyati tiplari ta’limoti asoschisi kim?", a: "I.Pavlov", b: "B.Teplov", c: "D.Nebilitsin", d: "A.Klimov", correct: "A" },
  { text: "Nerv sistemasining qaysi asosiy xususiyati qo‘zg‘alishdan tormozlanishgacha tez o‘tish bilan tavsiflanadi?", a: "qo‘zg‘aluvchanligi", b: "kuchiligi", c: "turg‘unligi", d: "kuchsizligi", correct: "A" },
  { text: "Temperament haqidagi ta’limot asoschisi, qadimgi yunon shifokori kim?", a: "Gippokrat", b: "Fales", c: "Spinoza", d: "Gobbs", correct: "A" },
  { text: "I.P.Pavlov insonlarni temperament tiplariga ajratishda qaysi omilni asos qilib olgan?", a: "oliy nerv faoliyatini", b: "shartsiz reflekslarni", c: "shartli reflekslarni", d: "signallar tizimini", correct: "A" },
  { text: "“O‘tning xususiyati qurug‘likdir uning vazifasi badanni quruq tutishdir”. Mazkur ta’rif qaysi tipga oid?", a: "xolerik", b: "sangivinik", c: "flegmatik", d: "melanxolik", correct: "A" },
  { text: "“Qonning xususiyati issiqlikdir uning vazifasi tanani issiq tutishdir”. Mazkur ta’rif qaysi tipga oid?", a: "sangivinik", b: "xolerik", c: "flegmatik", d: "melanxolik", correct: "A" },
  { text: "“Qora o‘tning xususiyati namlikdir, uning vazifasi badan namligini saqlab turishdir”. Mazkur ta’rif qaysi tipga oid?", a: "melanxolik", b: "sangivinik", c: "xolerik", d: "flegmatik", correct: "A" },
  { text: "“Balg‘amning xususiyati badanni sovutib turishdan iboratdir”. Mazkur ta’rif qaysi tipga oid?", a: "flegmatik", b: "sangivinik", c: "melanxolik", d: "xolerik", correct: "A" },
  { text: "K.Yung analitik psixologiyasining markaziy tushunchasi?", a: "arxetip", b: "ambivalentlik", c: "atributsiya", d: "agressiya", correct: "A" },
  { text: "Shaxsning psixik faoliyatida birinchi signallar tizimi ustunlik qilsa bu inson qanday tipga oid?", a: "badiiy tipga", b: "fikrlovchi tipga", c: "o‘rta tipga", d: "mulohazali tipga", correct: "A" },
  { text: "E.Krechmer bo'yicha atletik tipdagi insonlar qanday tana xususiyatlariga ega?", a: "skelet va mushaklar yaxshi rivojlangan, o‘rtadan yuqori baland bo‘yli, keng yelkali", b: "ozg‘in kishilar", c: "semirishga moyil", d: "kamgap, pessimist", correct: "A" },
  { text: "E.Krechmer bo'yicha piknik tipdagi insonlar qanday xususiyatlarga ega?", a: "bosh, ko‘krak qafasi yaxshi rivojlangan, semirishga moyil", b: "keng yelkali", c: "ozg‘in kishilar", d: "pessimist", correct: "A" },
  { text: "Qaysi qatorda xarakter xususiyatlari tarkibidagi tizimlar to‘g‘ri ko‘rsatilgan?", a: "mehnatga; narsalarga; odamning o‘z-o‘ziga; jamoaga bo‘lgan munosabat", b: "faqat mehnatga", c: "faqat narsalarga", d: "faqat jamoaga", correct: "A" },
  { text: "Qaysi qatorda jamoa va ayrim odamlarga bo‘lgan munosabatini ifodalovchi xususiyatlar keltirilgan?", a: "yaxshilik, mehribonlik, talabchanlik, takabburlik", b: "mehnatsevarlik, yalqovlik", c: "ozodalik, ifloslik", d: "izzat-nafslilik, mag‘rurlik", correct: "A" },
  { text: "Qaysi qatorda mehnatga bo‘lgan munosabatini ifodalovchi xususiyatlar keltirilgan?", a: "mehnatsevarlik, yalqovlik, vijdonlilik, mehnatga ma’suliyat", b: "yaxshilik, mehribonlik", c: "ozodalik, ifloslik", d: "izzat-nafslilik, mag‘rurlik", correct: "A" },
  { text: "Qaysi qatorda narsalarga bo‘lgan munosabatini ifodalovchi xususiyatlar keltirilgan?", a: "ozodalik yoki ifloslik, narsalar bilan ayab yoki ayamasdan munosabatda bo‘lish", b: "mehnatsevarlik, yalqovlik", c: "yaxshilik, mehribonlik", d: "izzat-nafslilik, mag‘rurlik", correct: "A" },
  { text: "Qaysi qatorda odamning o‘z-o‘ziga bo‘lgan munosabatini ifodalovchi xususiyatlar keltirilgan?", a: "izzat-nafslilik, shuhratparastlik, mag‘rurlik, o‘zini katta olish, kamtarlik", b: "mehnatsevarlik", c: "ozodalik", d: "yaxshilik", correct: "A" },

  // SECTION 7: 181-206
  { text: "Ona qornidagi rivojlanish bosqichini kamolot bosqichiga kiritgan tadqiqotchilar?", a: "A.Vallon, D.Bromley", b: "E.G‘oziyev, B.Qodirov", c: "D.B.Elkonin", d: "U.Sheldon", correct: "A" },
  { text: "Muayyan yoshlarning vujudga keltiruvchi ruhiy yangilanish, ya'ni inqiroz davrlari asosida yosh davrlari bosqichlarini belgilagan psixolog?", a: "Jean Piaget", b: "Lev Vygotsky", c: "Erik Erikson", d: "Sigmund Freud", correct: "B" },
  { text: "Yetakchi faoliyat nazariyasi asosida yosh davrlari belgilagan psixolog olim kim?", a: "B.G. Ananyev", b: "D.B. Elkonin", c: "L.I. Bojovich", d: "A.N. Leontyev", correct: "B" },
  { text: "Uilyam Sheldon tomonidan farqlangan tana tuzilishlari tiplarini belgilang.", a: "Sanguinik, Flegmatik", b: "Ekstrovert, Introvert", c: "Ektomorf, Mezomorf, Endomorf", d: "Normotenziv", correct: "C" },
  { text: "D.I.Feldsteyn bo'yicha shaxs shakllanishida ikkita muqtai nazar?", a: "individual va kollektiv", b: "ijtimoiy munosabatlar va individ", c: "biologik va psixologik", d: "ongli va ongsiz", correct: "B" },
  { text: "Ontogenez nima?", a: "Jamoa rivojlanishi", b: "Evolyutsion rivojlanish", c: "Organizmni tug'ilishidan to o'limigacha bo'lgan individual rivojlanish", d: "Madaniy rivojlanish", correct: "C" },
  { text: "Bog'cha yoshi davri qaysi yosh davriga to'g'ri keladi?", a: "1-3 yosh", b: "3-7 yosh", c: "7-11 yosh", d: "12-16 yosh", correct: "B" },
  { text: "Kichik maktab yoshi davrida asosiy yetakchi faoliyat qaysi?", a: "O'yin", b: "O'quv faoliyati", c: "Mehnat", d: "Muloqot", correct: "B" },
  { text: "Kichik maktab yoshidagi bolalarda xotiraning qaysi turi yaxshi rivojlangan bo'ladi?", a: "Mantiqiy", b: "Mexanik", c: "Ko'rgazmali-obrazli xotira", d: "Emotsional", correct: "C" },
  { text: "O'smirlarda qalqonsimon bez faoliyatining kuchayishi qanday holatlarni keltirib chiqaradi?", a: "Uyquchanlik", b: "Asabiylashish, injiqlik, kayfiyat o'zgarishi", c: "Xotirjamlik", d: "Kuchli ishtaha", correct: "B" },
  { text: "Bolada \"Men\"likni anglash necha yoshdan boshlanadi?", a: "1 yosh", b: "3 yoshdan", c: "5 yosh", d: "7 yosh", correct: "B" },
  { text: "Yangitug'ilgan chaqaloq vazni me'yorga ko'ra necha gramm bo'ladi?", a: "1500-2000", b: "2000-2500", c: "2500-4000 gramm", d: "4000-5000", correct: "C" },
  { text: "7 yoshda bola lug'atining so'z boyligi nechta so'zni tashkil etadi?", a: "500-1000", b: "1000-1500", c: "2000-3000", d: "3000-4000 so'z", correct: "C" },
  { text: "5-6 yoshli bolaga xos tafakkur qaysi to'g'ri ko'rsatilgan?", a: "Abstrakt-mantiqiy", b: "Faqat harakatli", c: "Ko'rgazmali-obrazli va so'z-mantiqiy", d: "Tanqdiiy", correct: "C" },
  { text: "Akseleratsiya – bu...", a: "Sekinlashish", b: "Bolalar va o'smirlarning jismoniy va psixik rivojlanishining tezlashishi", c: "To'xtash", d: "Genetika mutatsiya", correct: "B" },
  { text: "Psixogerantologiya – bu...", a: "Bolalar psixologiyasi", b: "Keksa yoshdagi odamlar psixologiyasini o'rganuvchi fan", c: "Sport psixologiyasi", d: "Uy hayvonlari psixologiyasi", correct: "B" },
  { text: "Ta'lim faoliyatining asosiy maqsadi – bu...", a: "Ijodiy qobiliyat", b: "Jismoniy rivojlanish", c: "Shaxsning har tomonlama rivojlanishi va bilimlarni egallash", d: "Axloqiy sifat", correct: "C" },
  { text: "O'quvchilarning o'zlashtira olmaslik sabablari qaysi qatorda to'g'ri keltirilgan?", a: "Faqat genetik", b: "Faqat iqtisodiy", c: "Individual psixologik xususiyatlar va ta'lim jarayonidagi kamchiliklar", d: "Faqat o'qituvchi", correct: "C" },
  { text: "Aqliy xatti-harakatlarni bosqichma-bosqich rivojlantirish nazariyasi muallifi?", a: "Jean Piaget", b: "Lev Vygotsky", c: "Pyotr Galperin", d: "Aleksey Leontyev", correct: "C" },
  { text: "Maktabga bolaning dezadaptatsiyasi – bu...", a: "A'lo baho", b: "Bolaning maktab muhitiga va munosabatlariga moslasha olmasligi", c: "Faol ishtirok", d: "Yangi do'stlar", correct: "B" },
  { text: "Tarbiya – bu...", a: "Faqat bilim", b: "Shaxsni maqsadga muvofiq shakllantirishga qaratilgan uzluksiz jarayon", c: "Jismoniy chiniqtirish", d: "O'z-o'zini rivojlantirish", correct: "B" },
  { text: "1-2 sinf o'quvchilarida idrokning o'ziga xos xususiyatlari qaysi?", a: "Faqat umumiy", b: "Butunlikdan ko'ra, qismlarga e'tibor berish", c: "Faqat aniq", d: "Diqqat barqarorligi", correct: "B" },
  { text: "Kichik maktab yoshida idrokdagi o'ziga xos qiyinchilik nimadan iborat?", a: "Barqarorlik", b: "Yuqori aniqlik", c: "Diqqatning beqarorligi, idrokning yuzaki va aniq emasligi", d: "Bir xil ob'ekt", correct: "C" },
  { text: "Shaxsning ekstrovert tipi – bu...", a: "Ichki dunyo", b: "His yashirish", c: "Energiyani tashqi dunyodan oladigan, ijtimoiy, faol shaxs", d: "Yolg'izlik", correct: "C" },
  { text: "Aqliy qobiliyatlar – bu...", a: "Jismoniy kuch", b: "Shaxsning bilish faoliyatini samarali amalga oshirishga imkon beruvchi xususiyatlar", c: "Emotsional intellekt", d: "Muloqot ko'nikmasi", correct: "B" },
  { text: "Taraqqiyot psixologiyasi – bu...", a: "Faqat bolalar", b: "Faqat o'smirlar", c: "Insonning tug'ilishidan to o'limigacha bo'lgan psixik o'zgarishlarni o'rganuvchi fan", d: "Faqat kattalar", correct: "C" },
];

export const QUESTIONS: Question[] = rawQuestions.map((q, index) => ({
  id: index + 1,
  text: q.text,
  options: {
    A: q.a,
    B: q.b,
    C: q.c,
    D: q.d,
  },
  correctAnswer: q.correct as 'A' | 'B' | 'C' | 'D',
}));

export const SECTIONS: Section[] = [
  { id: 1, name: "Psixologiya tarixi va metodlari", startId: 1, endId: 30, totalQuestions: 30 },
  { id: 2, name: "Faoliyat va Ong", startId: 31, endId: 60, totalQuestions: 30 },
  { id: 3, name: "Sezgi va Idrok", startId: 61, endId: 90, totalQuestions: 30 },
  { id: 4, name: "Diqqat va Xotira", startId: 91, endId: 120, totalQuestions: 30 },
  { id: 5, name: "Tafakkur va Nutq", startId: 121, endId: 150, totalQuestions: 30 },
  { id: 6, name: "Emotsiya, Motiv va Iroda", startId: 151, endId: 180, totalQuestions: 30 },
  { id: 7, name: "Shaxs va Taraqqiyot Psixologiyasi", startId: 181, endId: 206, totalQuestions: 26 },
];
